<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<?xml-stylesheet ekr_test ?>
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="amd.20150913232631.1"><vh>@settings</vh>
<v t="amd.20150913232631.2"><vh>@data qt-gui-plugin-style-sheet</vh></v>
<v t="amd.20150913232631.3"><vh>@string initial_split_orientation = horizontal</vh></v>
</v>
<v t="amd.20150919102739.1"><vh>專案架構</vh>
<v t="amd.20150919113520.1"><vh>@edit .gitignore</vh></v>
<v t="amd.20151007224830.1"><vh>Jupyter 安裝與執行</vh></v>
<v t="amd.20150919103357.1"><vh>pelican 設定</vh></v>
</v>
<v t="123.20151208171418.1" a="E"><vh>以下為 pelican 文章</vh>
<v t="123.20151208171418.2"><vh>@button user pelican</vh></v>
<v t="123.20151208171418.3" a="E"><vh>@path pelican</vh>
<v t="40323217.20151229164040.1"><vh>@edit publishconf.py</vh></v>
<v t="40323217.20151229164314.1" a="E"><vh>@path content</vh>
<v t="40323217.20151229164314.2"><vh>@edit 2015cphww1.md</vh></v>
<v t="40323217.20151229164314.3"><vh>@edit 2015cpnote1.md</vh></v>
<v t="40323217.20151229164314.4"><vh>@edit 2015cphww4.md</vh></v>
<v t="40323217.20151229164314.5"><vh>@edit 2015cphww5.md</vh></v>
<v t="40323217.20151229201414.1"><vh>@edit 2015cphww6.md</vh></v>
<v t="40323217.20151229201930.1"><vh>@edit 2015cphww7.md</vh></v>
<v t="40323217.20151229202054.1"><vh>@edit 2015cphww8.md</vh></v>
<v t="40323217.20151229202151.1"><vh>@edit 2015cphww10.md</vh></v>
<v t="40323217.20151229164314.6"><vh>@edit 2015cphww11.md</vh></v>
<v t="40323217.20151229164314.7"><vh>@edit 2015cphww12.md</vh></v>
<v t="40323217.20151229164314.8"><vh>@edit 2015cphww13.md</vh></v>
<v t="40323217.20151229164314.9"><vh>@edit 2015cphww14.md</vh></v>
<v t="40323217.20151229164314.10"><vh>@edit 2015cphww15.md</vh></v>
<v t="40323217.20160104214755.1"><vh>@edit 2015cphww16.md</vh></v>
</v>
</v>
</v>
<v t="123.20151208171423.1" a="E"><vh>以下為 reveal 投影片</vh>
<v t="40323217.20151229164517.1"><vh>@clean cadpbw1.html</vh>
<v t="40323217.20151229164517.2"><vh>html</vh>
<v t="40323217.20151229164517.3"><vh>head</vh>
<v t="40323217.20151229164517.4"><vh>title</vh></v>
</v>
<v t="40323217.20151229164517.5"><vh>body</vh>
<v t="40323217.20151229164517.6"><vh>div</vh>
<v t="40323217.20151229164517.7"><vh>div</vh>
<v t="40323217.20151229164517.8"><vh>title page</vh>
<v t="40323217.20151229164517.9"><vh>標題頁下的子頁</vh></v>
</v>
<v t="40323217.20151229164517.10"><vh>本日要點</vh></v>
<v t="40323217.20151229164517.11"><vh>Anaconda Python</vh></v>
<v t="40323217.20151229164517.12"><vh>設計的表達方式</vh>
<v t="40323217.20151229164517.13"><vh>協同模式下的網際雲端內容呈現</vh></v>
</v>
<v t="40323217.20151229164517.14"><vh>結論</vh></v>
</v>
</v>
<v t="40323217.20151229164517.15"><vh>script</vh></v>
<v t="40323217.20151229164517.16"><vh>script</vh></v>
<v t="40323217.20151229164517.17"><vh>script</vh></v>
</v>
</v>
</v>
<v t="40323217.20151229164524.1"><vh>@clean cadpaw1.html</vh>
<v t="40323217.20151229164524.2"><vh>html 標註</vh>
<v t="40323217.20151229164524.3"><vh>head</vh>
<v t="40323217.20151229164524.4"><vh>title - 標題</vh></v>
<v t="40323217.20151229164524.5"><vh>meta - 說明</vh></v>
<v t="40323217.20151229164524.6"><vh>script - css 與 pdf 列印</vh></v>
</v>
<v t="40323217.20151229164524.7"><vh>body</vh>
<v t="40323217.20151229164524.8"><vh>div - reveal</vh>
<v t="40323217.20151229164524.9"><vh>div - slides</vh>
<v t="40323217.20151229164524.10"><vh>h1 - 課程說明</vh></v>
<v t="40323217.20151229164524.11"><vh>h1 - 開放自評規劃</vh></v>
<v t="40323217.20151229164524.12"><vh>h2 - 實體輔助工具</vh></v>
<v t="40323217.20151229164524.13"><vh>h2 - 垂直有下屬頁</vh>
<v t="40323217.20151229164524.14"><vh>h2</vh></v>
<v t="40323217.20151229164524.15"><vh>h2</vh></v>
<v t="40323217.20151229164524.16"><vh>h2</vh></v>
</v>
<v t="40323217.20151229164524.17"><vh>h2 - 內含程式碼頁面</vh>
<v t="40323217.20151229164524.18"><vh>pre</vh>
<v t="40323217.20151229164524.19"><vh>code</vh></v>
</v>
<v t="40323217.20151229164524.20"><vh>p</vh></v>
</v>
<v t="40323217.20151229164524.21"><vh>h2</vh></v>
<v t="40323217.20151229164524.22"><vh>內嵌 Vimeo 影片</vh></v>
<v t="40323217.20151229164524.23"><vh>h2</vh></v>
<v t="40323217.20151229164524.24"><vh>h2</vh></v>
<v t="40323217.20151229164524.25"><vh>markdown 頁面</vh></v>
<v t="40323217.20151229164524.26"><vh>h2</vh>
<v t="40323217.20151229164524.27"><vh>Fragement 主頁面</vh></v>
<v t="40323217.20151229164524.28"><vh>下屬頁面</vh>
<v t="40323217.20151229164524.29"><vh>h2</vh></v>
<v t="40323217.20151229164524.30"><vh>p</vh></v>
<v t="40323217.20151229164524.31"><vh>p</vh></v>
<v t="40323217.20151229164524.32"><vh>p</vh></v>
<v t="40323217.20151229164524.33"><vh>p</vh></v>
<v t="40323217.20151229164524.34"><vh>p</vh></v>
<v t="40323217.20151229164524.35"><vh>p</vh></v>
<v t="40323217.20151229164524.36"><vh>p</vh></v>
</v>
</v>
<v t="40323217.20151229164524.37"><vh>h2</vh></v>
<v t="40323217.20151229164524.38"><vh>p</vh>
<v t="40323217.20151229164524.39"><vh>a</vh></v>
<v t="40323217.20151229164524.40"><vh>a</vh></v>
<v t="40323217.20151229164524.41"><vh>a</vh></v>
<v t="40323217.20151229164524.42"><vh>a</vh></v>
<v t="40323217.20151229164524.43"><vh>a</vh></v>
<v t="40323217.20151229164524.44"><vh>a</vh></v>
</v>
<v t="40323217.20151229164524.45"><vh>h2 - 更換主題</vh></v>
<v t="40323217.20151229164524.46"><vh>p</vh>
<v t="40323217.20151229164524.47"><vh>a</vh></v>
<v t="40323217.20151229164524.48"><vh>a</vh></v>
<v t="40323217.20151229164524.49"><vh>a</vh></v>
<v t="40323217.20151229164524.50"><vh>a</vh></v>
<v t="40323217.20151229164524.51"><vh>a</vh></v>
<v t="40323217.20151229164524.52"><vh>a</vh></v>
<v t="40323217.20151229164524.53"><vh>a</vh></v>
<v t="40323217.20151229164524.54"><vh>a</vh></v>
<v t="40323217.20151229164524.55"><vh>a</vh></v>
<v t="40323217.20151229164524.56"><vh>a</vh></v>
<v t="40323217.20151229164524.57"><vh>a</vh></v>
</v>
<v t="40323217.20151229164524.58"><vh>h2</vh></v>
<v t="40323217.20151229164524.59"><vh>p</vh>
<v t="40323217.20151229164524.60"><vh>code</vh></v>
</v>
<v t="40323217.20151229164524.61"><vh>a</vh></v>
<v t="40323217.20151229164524.62"><vh>h2</vh></v>
<v t="40323217.20151229164524.63"><vh>pre</vh>
<v t="40323217.20151229164524.64"><vh>code</vh></v>
</v>
<v t="40323217.20151229164524.65"><vh>h2 - 背景填圖頁面</vh></v>
<v t="40323217.20151229164524.66"><vh>pre</vh>
<v t="40323217.20151229164524.67"><vh>code</vh></v>
</v>
<v t="40323217.20151229164524.68"><vh>div</vh>
<v t="40323217.20151229164524.69"><vh>h2</vh></v>
<v t="40323217.20151229164524.70"><vh>pre</vh>
<v t="40323217.20151229164524.71"><vh>code</vh></v>
</v>
</v>
<v t="40323217.20151229164524.72"><vh>h2</vh></v>
<v t="40323217.20151229164524.73"><vh>h2</vh></v>
<v t="40323217.20151229164524.74"><vh>p</vh></v>
<v t="40323217.20151229164524.75"><vh>pre</vh>
<v t="40323217.20151229164524.76"><vh>code</vh></v>
</v>
<v t="40323217.20151229164524.77"><vh>h2 - 背景轉換</vh></v>
<v t="40323217.20151229164524.78"><vh>p</vh></v>
<v t="40323217.20151229164524.79"><vh>pre</vh>
<v t="40323217.20151229164524.80"><vh>code</vh></v>
</v>
<v t="40323217.20151229164524.81"><vh>h2 - 內含程式碼頁面</vh>
<v t="40323217.20151229164524.82"><vh>pre</vh>
<v t="40323217.20151229164524.83"><vh>code</vh></v>
</v>
<v t="40323217.20151229164524.84"><vh>p</vh></v>
</v>
<v t="40323217.20151229164524.85"><vh>h2</vh></v>
<v t="40323217.20151229164524.86"><vh>ul</vh>
<v t="40323217.20151229164524.87"><vh>li</vh></v>
<v t="40323217.20151229164524.88"><vh>li</vh></v>
<v t="40323217.20151229164524.89"><vh>li</vh></v>
<v t="40323217.20151229164524.90"><vh>li</vh></v>
</v>
<v t="40323217.20151229164524.91"><vh>h2</vh></v>
<v t="40323217.20151229164524.92"><vh>ol</vh>
<v t="40323217.20151229164524.93"><vh>li</vh></v>
<v t="40323217.20151229164524.94"><vh>li</vh></v>
<v t="40323217.20151229164524.95"><vh>li</vh></v>
</v>
<v t="40323217.20151229164524.96"><vh>h2 - 表格頁面</vh></v>
<v t="40323217.20151229164524.97"><vh>table</vh>
<v t="40323217.20151229164524.98"><vh>thead</vh>
<v t="40323217.20151229164524.99"><vh>tr</vh>
<v t="40323217.20151229164524.100"><vh>th</vh></v>
<v t="40323217.20151229164524.101"><vh>th</vh></v>
<v t="40323217.20151229164524.102"><vh>th</vh></v>
</v>
</v>
<v t="40323217.20151229164524.103"><vh>tbody</vh>
<v t="40323217.20151229164524.104"><vh>tr</vh>
<v t="40323217.20151229164524.105"><vh>td</vh></v>
<v t="40323217.20151229164524.106"><vh>td</vh></v>
<v t="40323217.20151229164524.107"><vh>td</vh></v>
</v>
<v t="40323217.20151229164524.108"><vh>tr</vh>
<v t="40323217.20151229164524.109"><vh>td</vh></v>
<v t="40323217.20151229164524.110"><vh>td</vh></v>
<v t="40323217.20151229164524.111"><vh>td</vh></v>
</v>
<v t="40323217.20151229164524.112"><vh>tr</vh>
<v t="40323217.20151229164524.113"><vh>td</vh></v>
<v t="40323217.20151229164524.114"><vh>td</vh></v>
<v t="40323217.20151229164524.115"><vh>td</vh></v>
</v>
</v>
</v>
<v t="40323217.20151229164524.116"><vh>h2</vh></v>
<v t="40323217.20151229164524.117"><vh>p</vh>
<v t="40323217.20151229164524.118"><vh>q</vh></v>
</v>
<v t="40323217.20151229164524.119"><vh>blockquote</vh></v>
<v t="40323217.20151229164524.120"><vh>h2</vh></v>
<v t="40323217.20151229164524.121"><vh>p</vh>
<v t="40323217.20151229164524.122"><vh>a</vh></v>
</v>
<v t="40323217.20151229164524.123"><vh>h2</vh></v>
<v t="40323217.20151229164524.124"><vh>p</vh>
<v t="40323217.20151229164524.125"><vh>a</vh></v>
</v>
<v t="40323217.20151229164524.126"><vh>p</vh>
<v t="40323217.20151229164524.127"><vh>em</vh></v>
</v>
<v t="40323217.20151229164524.128"><vh>h2</vh></v>
<v t="40323217.20151229164524.129"><vh>p</vh>
<v t="40323217.20151229164524.130"><vh>a</vh></v>
</v>
<v t="40323217.20151229164524.131"><vh>iframe</vh></v>
<v t="40323217.20151229164524.132"><vh>h2</vh></v>
<v t="40323217.20151229164524.133"><vh>p</vh>
<v t="40323217.20151229164524.134"><vh>code</vh></v>
<v t="40323217.20151229164524.135"><vh>code</vh></v>
</v>
<v t="40323217.20151229164524.136"><vh>h2</vh></v>
<v t="40323217.20151229164524.137"><vh>p</vh>
<v t="40323217.20151229164524.138"><vh>code</vh></v>
</v>
<v t="40323217.20151229164524.139"><vh>pre</vh>
<v t="40323217.20151229164524.140"><vh>code</vh></v>
</v>
<v t="40323217.20151229164524.141"><vh>h2 按下 b 或 . 可以 black 畫面</vh></v>
<v t="40323217.20151229164524.142"><vh>p</vh></v>
<v t="40323217.20151229164524.143"><vh>h2 unordered list 頁面</vh>
<v t="40323217.20151229164524.144"><vh>li</vh>
<v t="40323217.20151229164524.145"><vh>a</vh></v>
</v>
<v t="40323217.20151229164524.146"><vh>li</vh>
<v t="40323217.20151229164524.147"><vh>a</vh></v>
</v>
<v t="40323217.20151229164524.148"><vh>li</vh>
<v t="40323217.20151229164524.149"><vh>a</vh></v>
</v>
<v t="40323217.20151229164524.150"><vh>li</vh>
<v t="40323217.20151229164524.151"><vh>a</vh></v>
</v>
<v t="40323217.20151229164524.152"><vh>li</vh></v>
</v>
<v t="40323217.20151229164524.153"><vh>結束單頁</vh></v>
</v>
</v>
<v t="40323217.20151229164524.154"><vh>script</vh></v>
<v t="40323217.20151229164524.155"><vh>script</vh></v>
<v t="40323217.20151229164524.156"><vh>script</vh></v>
</v>
</v>
</v>
<v t="40323217.20151229164529.1"><vh>@clean cpw1.html</vh>
<v t="40323217.20151229164529.2"><vh>檔案說明</vh></v>
<v t="40323217.20151229164529.3"><vh>html 標註</vh>
<v t="40323217.20151229164529.4"><vh>body 標註</vh>
<v t="40323217.20151229164529.5"><vh>div class="reveal"</vh>
<v t="40323217.20151229164529.6"><vh>div class="slides"</vh>
<v t="40323217.20151229164529.7"><vh>有關我的作業</vh></v>
<v t="40323217.20151229164529.8"><vh>課程規劃</vh></v>
<v t="40323217.20151229164529.9"><vh>作業規劃</vh></v>
<v t="40323217.20151229164529.10"><vh>Git 操作</vh></v>
<v t="40323217.20151229164529.11"><vh>Jupyter 操作</vh></v>
<v t="40323217.20151229164529.12"><vh>結論</vh></v>
</v>
</v>
<v t="40323217.20151229164529.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="40323217.20151229164557.1"><vh>@clean simplest.html</vh>
<v t="40323217.20151229164557.2"><vh>檔案說明</vh></v>
<v t="40323217.20151229164557.3"><vh>html 標註</vh>
<v t="40323217.20151229164557.4"><vh>body 標註</vh>
<v t="40323217.20151229164557.5"><vh>div class="reveal"</vh>
<v t="40323217.20151229164557.6"><vh>div class="slides"</vh>
<v t="40323217.20151229164557.7"><vh>有關我的作業</vh></v>
<v t="40323217.20151229164557.8"><vh>作業任務一</vh></v>
<v t="40323217.20151229164557.9"><vh>第3張投影片</vh></v>
</v>
</v>
<v t="40323217.20151229164557.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="40323217.20151229164603.1"><vh>@clean simplest2.html</vh>
<v t="40323217.20151229164603.2"><vh>檔案說明</vh></v>
<v t="40323217.20151229164603.3" a="E"><vh>html 標註</vh>
<v t="40323217.20151229164603.4" a="E"><vh>body 標註</vh>
<v t="40323217.20151229164603.5" a="E"><vh>div class="reveal"</vh>
<v t="40323217.20151229164603.6" a="E"><vh>div class="slides"</vh>
<v t="40323217.20151229164603.7"><vh>有關我的作業</vh></v>
<v t="40323217.20151229164603.8"><vh>作業任務一</vh></v>
<v t="40323217.20151229164603.9"><vh>第3張投影片</vh></v>
</v>
</v>
<v t="40323217.20151229164603.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="40323217.20151229164608.1"><vh>@clean simplest3.html</vh>
<v t="40323217.20151229164608.2"><vh>檔案說明</vh></v>
<v t="40323217.20151229164608.3" a="E"><vh>html 標註</vh>
<v t="40323217.20151229164608.4" a="E"><vh>body 標註</vh>
<v t="40323217.20151229164608.5" a="E"><vh>div class="reveal"</vh>
<v t="40323217.20151229164608.6" a="E"><vh>div class="slides"</vh>
<v t="40323217.20151229164608.7"><vh>有關我的作業</vh></v>
<v t="40323217.20151229164608.8"><vh>作業任務一</vh></v>
<v t="40323217.20151229164608.9"><vh>第3張投影片</vh></v>
</v>
</v>
<v t="40323217.20151229164608.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="40323217.20151229201516.1"><vh>@clean simplest6.html</vh>
<v t="40323217.20151229201516.2"><vh>檔案說明</vh></v>
<v t="40323217.20151229201516.3" a="E"><vh>html 標註</vh>
<v t="40323217.20151229201516.4" a="E"><vh>body 標註</vh>
<v t="40323217.20151229201516.5" a="E"><vh>div class="reveal"</vh>
<v t="40323217.20151229201516.6" a="E"><vh>div class="slides"</vh>
<v t="40323217.20151229201516.7"><vh>有關我的作業</vh></v>
<v t="40323217.20151229201516.8"><vh>作業任務一</vh></v>
<v t="40323217.20151229201516.9"><vh>第3張投影片</vh></v>
</v>
</v>
<v t="40323217.20151229201516.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="40323217.20151229202015.1"><vh>@clean simplest7.html</vh>
<v t="40323217.20151229202015.2"><vh>檔案說明</vh></v>
<v t="40323217.20151229202015.3" a="E"><vh>html 標註</vh>
<v t="40323217.20151229202015.4" a="E"><vh>body 標註</vh>
<v t="40323217.20151229202015.5" a="E"><vh>div class="reveal"</vh>
<v t="40323217.20151229202015.6" a="E"><vh>div class="slides"</vh>
<v t="40323217.20151229202015.7"><vh>有關我的作業</vh></v>
<v t="40323217.20151229202015.8"><vh>作業任務一</vh></v>
<v t="40323217.20151229202015.9"><vh>第3張投影片</vh></v>
</v>
</v>
<v t="40323217.20151229202015.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="40323217.20151229202138.1"><vh>@clean simplest8.html</vh>
<v t="40323217.20151229202138.2"><vh>檔案說明</vh></v>
<v t="40323217.20151229202138.3" a="E"><vh>html 標註</vh>
<v t="40323217.20151229202138.4" a="E"><vh>body 標註</vh>
<v t="40323217.20151229202138.5" a="E"><vh>div class="reveal"</vh>
<v t="40323217.20151229202138.6" a="E"><vh>div class="slides"</vh>
<v t="40323217.20151229202138.7"><vh>有關我的作業</vh></v>
<v t="40323217.20151229202138.8"><vh>作業任務一</vh></v>
<v t="40323217.20151229202138.9"><vh>第3張投影片</vh></v>
</v>
</v>
<v t="40323217.20151229202138.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="40323217.20151229202232.1"><vh>@clean simplest10.html</vh>
<v t="40323217.20151229202232.2"><vh>檔案說明</vh></v>
<v t="40323217.20151229202232.3" a="E"><vh>html 標註</vh>
<v t="40323217.20151229202232.4" a="E"><vh>body 標註</vh>
<v t="40323217.20151229202232.5" a="E"><vh>div class="reveal"</vh>
<v t="40323217.20151229202232.6" a="E"><vh>div class="slides"</vh>
<v t="40323217.20151229202232.7"><vh>有關我的作業</vh></v>
<v t="40323217.20151229202232.8"><vh>作業任務一</vh></v>
<v t="40323217.20151229202232.9"><vh>第3張投影片</vh></v>
</v>
</v>
<v t="40323217.20151229202232.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="40323217.20151229164612.1"><vh>@clean simplest11.html</vh>
<v t="40323217.20151229164612.2"><vh>檔案說明</vh></v>
<v t="40323217.20151229164612.3" a="E"><vh>html 標註</vh>
<v t="40323217.20151229164612.4" a="E"><vh>body 標註</vh>
<v t="40323217.20151229164612.5" a="E"><vh>div class="reveal"</vh>
<v t="40323217.20151229164612.6" a="E"><vh>div class="slides"</vh>
<v t="40323217.20151229164612.7"><vh>有關我的作業</vh></v>
<v t="40323217.20151229164612.8"><vh>作業任務一</vh></v>
<v t="40323217.20151229164612.9"><vh>第3張投影片</vh></v>
</v>
</v>
<v t="40323217.20151229164612.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="40323217.20151229164617.1"><vh>@clean simplest12.html</vh>
<v t="40323217.20151229164617.2"><vh>檔案說明</vh></v>
<v t="40323217.20151229164617.3" a="E"><vh>html 標註</vh>
<v t="40323217.20151229164617.4" a="E"><vh>body 標註</vh>
<v t="40323217.20151229164617.5" a="E"><vh>div class="reveal"</vh>
<v t="40323217.20151229164617.6" a="E"><vh>div class="slides"</vh>
<v t="40323217.20151229164617.7"><vh>有關我的作業</vh></v>
<v t="40323217.20151229164617.8"><vh>作業任務一</vh></v>
<v t="40323217.20151229164617.9"><vh>第3張投影片</vh></v>
</v>
</v>
<v t="40323217.20151229164617.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="40323217.20151229164621.1"><vh>@clean simplest13.html</vh>
<v t="40323217.20151229164621.2"><vh>檔案說明</vh></v>
<v t="40323217.20151229164621.3" a="E"><vh>html 標註</vh>
<v t="40323217.20151229164621.4" a="E"><vh>body 標註</vh>
<v t="40323217.20151229164621.5" a="E"><vh>div class="reveal"</vh>
<v t="40323217.20151229164621.6" a="E"><vh>div class="slides"</vh>
<v t="40323217.20151229164621.7"><vh>有關我的作業</vh></v>
<v t="40323217.20151229164621.8"><vh>作業任務一</vh></v>
<v t="40323217.20151229164621.9"><vh>第3張投影片</vh></v>
</v>
</v>
<v t="40323217.20151229164621.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="40323217.20151229164630.1"><vh>@clean simplest15.html</vh>
<v t="40323217.20151229164630.2"><vh>檔案說明</vh></v>
<v t="40323217.20151229164630.3" a="E"><vh>html 標註</vh>
<v t="40323217.20151229164630.4" a="E"><vh>body 標註</vh>
<v t="40323217.20151229164630.5" a="E"><vh>div class="reveal"</vh>
<v t="40323217.20151229164630.6" a="E"><vh>div class="slides"</vh>
<v t="40323217.20151229164630.7"><vh>有關我的作業</vh></v>
<v t="40323217.20151229164630.8"><vh>作業任務一</vh></v>
<v t="40323217.20151229164630.9"><vh>第3張投影片</vh></v>
</v>
</v>
<v t="40323217.20151229164630.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="40323217.20151229164625.1"><vh>@clean simplest14.html</vh>
<v t="40323217.20151229164625.2"><vh>檔案說明</vh></v>
<v t="40323217.20151229164625.3" a="E"><vh>html 標註</vh>
<v t="40323217.20151229164625.4" a="E"><vh>body 標註</vh>
<v t="40323217.20151229164625.5" a="E"><vh>div class="reveal"</vh>
<v t="40323217.20151229164625.6" a="E"><vh>div class="slides"</vh>
<v t="40323217.20151229164625.7"><vh>有關我的作業</vh></v>
<v t="40323217.20151229164625.8"><vh>作業任務一</vh></v>
<v t="40323217.20151229164625.9"><vh>第3張投影片</vh></v>
</v>
</v>
<v t="40323217.20151229164625.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="40323217.20160104214807.1"><vh>@clean simplest16.html</vh>
<v t="40323217.20160104214807.2"><vh>檔案說明</vh></v>
<v t="40323217.20160104214807.3" a="E"><vh>html 標註</vh>
<v t="40323217.20160104214807.4" a="E"><vh>body 標註</vh>
<v t="40323217.20160104214807.5" a="E"><vh>div class="reveal"</vh>
<v t="40323217.20160104214807.6" a="E"><vh>div class="slides"</vh>
<v t="40323217.20160104214807.7"><vh>有關我的作業</vh></v>
<v t="40323217.20160104214807.8"><vh>作業任務一</vh></v>
<v t="40323217.20160104214807.9"><vh>第3張投影片</vh></v>
</v>
</v>
<v t="40323217.20160104214807.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="40323217.20151229164536.1"><vh>@clean v31ref.html</vh>
<v t="40323217.20151229164536.2"><vh>html 標註</vh>
<v t="40323217.20151229164536.3"><vh>head</vh>
<v t="40323217.20151229164536.4"><vh>title - 標題</vh></v>
<v t="40323217.20151229164536.5"><vh>meta - 說明</vh></v>
<v t="40323217.20151229164536.6"><vh>script - css 與 pdf 列印</vh></v>
</v>
<v t="40323217.20151229164536.7"><vh>body</vh>
<v t="40323217.20151229164536.8"><vh>div - reveal</vh>
<v t="40323217.20151229164536.9"><vh>div - slides</vh>
<v t="40323217.20151229164536.10"><vh>h1 - 一般單頁</vh></v>
<v t="40323217.20151229164536.11"><vh>h2</vh></v>
<v t="40323217.20151229164536.12"><vh>h2 - 垂直有下屬頁</vh>
<v t="40323217.20151229164536.13"><vh>h2</vh></v>
<v t="40323217.20151229164536.14"><vh>h2</vh></v>
<v t="40323217.20151229164536.15"><vh>h2</vh></v>
</v>
<v t="40323217.20151229164536.16"><vh>h2</vh></v>
<v t="40323217.20151229164536.17"><vh>h2</vh></v>
<v t="40323217.20151229164536.18"><vh>h2</vh></v>
<v t="40323217.20151229164536.19"><vh>markdown 頁面</vh></v>
<v t="40323217.20151229164536.20"><vh>h2</vh>
<v t="40323217.20151229164536.21"><vh>Fragement 主頁面</vh></v>
<v t="40323217.20151229164536.22"><vh>下屬頁面</vh>
<v t="40323217.20151229164536.23"><vh>h2</vh></v>
<v t="40323217.20151229164536.24"><vh>p</vh></v>
<v t="40323217.20151229164536.25"><vh>p</vh></v>
<v t="40323217.20151229164536.26"><vh>p</vh></v>
<v t="40323217.20151229164536.27"><vh>p</vh></v>
<v t="40323217.20151229164536.28"><vh>p</vh></v>
<v t="40323217.20151229164536.29"><vh>p</vh></v>
<v t="40323217.20151229164536.30"><vh>p</vh></v>
</v>
</v>
<v t="40323217.20151229164536.31"><vh>h2</vh></v>
<v t="40323217.20151229164536.32"><vh>p</vh>
<v t="40323217.20151229164536.33"><vh>a</vh></v>
<v t="40323217.20151229164536.34"><vh>a</vh></v>
<v t="40323217.20151229164536.35"><vh>a</vh></v>
<v t="40323217.20151229164536.36"><vh>a</vh></v>
<v t="40323217.20151229164536.37"><vh>a</vh></v>
<v t="40323217.20151229164536.38"><vh>a</vh></v>
</v>
<v t="40323217.20151229164536.39"><vh>h2 - 更換主題</vh></v>
<v t="40323217.20151229164536.40"><vh>p</vh>
<v t="40323217.20151229164536.41"><vh>a</vh></v>
<v t="40323217.20151229164536.42"><vh>a</vh></v>
<v t="40323217.20151229164536.43"><vh>a</vh></v>
<v t="40323217.20151229164536.44"><vh>a</vh></v>
<v t="40323217.20151229164536.45"><vh>a</vh></v>
<v t="40323217.20151229164536.46"><vh>a</vh></v>
<v t="40323217.20151229164536.47"><vh>a</vh></v>
<v t="40323217.20151229164536.48"><vh>a</vh></v>
<v t="40323217.20151229164536.49"><vh>a</vh></v>
<v t="40323217.20151229164536.50"><vh>a</vh></v>
<v t="40323217.20151229164536.51"><vh>a</vh></v>
</v>
<v t="40323217.20151229164536.52"><vh>h2</vh></v>
<v t="40323217.20151229164536.53"><vh>p</vh>
<v t="40323217.20151229164536.54"><vh>code</vh></v>
</v>
<v t="40323217.20151229164536.55"><vh>a</vh></v>
<v t="40323217.20151229164536.56"><vh>h2</vh></v>
<v t="40323217.20151229164536.57"><vh>pre</vh>
<v t="40323217.20151229164536.58"><vh>code</vh></v>
</v>
<v t="40323217.20151229164536.59"><vh>h2 - 背景填圖頁面</vh></v>
<v t="40323217.20151229164536.60"><vh>pre</vh>
<v t="40323217.20151229164536.61"><vh>code</vh></v>
</v>
<v t="40323217.20151229164536.62"><vh>div</vh>
<v t="40323217.20151229164536.63"><vh>h2</vh></v>
<v t="40323217.20151229164536.64"><vh>pre</vh>
<v t="40323217.20151229164536.65"><vh>code</vh></v>
</v>
</v>
<v t="40323217.20151229164536.66"><vh>h2</vh></v>
<v t="40323217.20151229164536.67"><vh>h2</vh></v>
<v t="40323217.20151229164536.68"><vh>p</vh></v>
<v t="40323217.20151229164536.69"><vh>pre</vh>
<v t="40323217.20151229164536.70"><vh>code</vh></v>
</v>
<v t="40323217.20151229164536.71"><vh>h2 - 背景轉換</vh></v>
<v t="40323217.20151229164536.72"><vh>p</vh></v>
<v t="40323217.20151229164536.73"><vh>pre</vh>
<v t="40323217.20151229164536.74"><vh>code</vh></v>
</v>
<v t="40323217.20151229164536.75"><vh>h2 - 內含程式碼頁面</vh>
<v t="40323217.20151229164536.76"><vh>pre</vh>
<v t="40323217.20151229164536.77"><vh>code</vh></v>
</v>
<v t="40323217.20151229164536.78"><vh>p</vh></v>
</v>
<v t="40323217.20151229164536.79"><vh>h2</vh></v>
<v t="40323217.20151229164536.80"><vh>ul</vh>
<v t="40323217.20151229164536.81"><vh>li</vh></v>
<v t="40323217.20151229164536.82"><vh>li</vh></v>
<v t="40323217.20151229164536.83"><vh>li</vh></v>
<v t="40323217.20151229164536.84"><vh>li</vh></v>
</v>
<v t="40323217.20151229164536.85"><vh>h2</vh></v>
<v t="40323217.20151229164536.86"><vh>ol</vh>
<v t="40323217.20151229164536.87"><vh>li</vh></v>
<v t="40323217.20151229164536.88"><vh>li</vh></v>
<v t="40323217.20151229164536.89"><vh>li</vh></v>
</v>
<v t="40323217.20151229164536.90"><vh>h2 - 表格頁面</vh></v>
<v t="40323217.20151229164536.91"><vh>table</vh>
<v t="40323217.20151229164536.92"><vh>thead</vh>
<v t="40323217.20151229164536.93"><vh>tr</vh>
<v t="40323217.20151229164536.94"><vh>th</vh></v>
<v t="40323217.20151229164536.95"><vh>th</vh></v>
<v t="40323217.20151229164536.96"><vh>th</vh></v>
</v>
</v>
<v t="40323217.20151229164536.97"><vh>tbody</vh>
<v t="40323217.20151229164536.98"><vh>tr</vh>
<v t="40323217.20151229164536.99"><vh>td</vh></v>
<v t="40323217.20151229164536.100"><vh>td</vh></v>
<v t="40323217.20151229164536.101"><vh>td</vh></v>
</v>
<v t="40323217.20151229164536.102"><vh>tr</vh>
<v t="40323217.20151229164536.103"><vh>td</vh></v>
<v t="40323217.20151229164536.104"><vh>td</vh></v>
<v t="40323217.20151229164536.105"><vh>td</vh></v>
</v>
<v t="40323217.20151229164536.106"><vh>tr</vh>
<v t="40323217.20151229164536.107"><vh>td</vh></v>
<v t="40323217.20151229164536.108"><vh>td</vh></v>
<v t="40323217.20151229164536.109"><vh>td</vh></v>
</v>
</v>
</v>
<v t="40323217.20151229164536.110"><vh>h2</vh></v>
<v t="40323217.20151229164536.111"><vh>p</vh>
<v t="40323217.20151229164536.112"><vh>q</vh></v>
</v>
<v t="40323217.20151229164536.113"><vh>blockquote</vh></v>
<v t="40323217.20151229164536.114"><vh>h2</vh></v>
<v t="40323217.20151229164536.115"><vh>p</vh>
<v t="40323217.20151229164536.116"><vh>a</vh></v>
</v>
<v t="40323217.20151229164536.117"><vh>h2</vh></v>
<v t="40323217.20151229164536.118"><vh>p</vh>
<v t="40323217.20151229164536.119"><vh>a</vh></v>
</v>
<v t="40323217.20151229164536.120"><vh>p</vh>
<v t="40323217.20151229164536.121"><vh>em</vh></v>
</v>
<v t="40323217.20151229164536.122"><vh>h2</vh></v>
<v t="40323217.20151229164536.123"><vh>p</vh>
<v t="40323217.20151229164536.124"><vh>a</vh></v>
</v>
<v t="40323217.20151229164536.125"><vh>iframe</vh></v>
<v t="40323217.20151229164536.126"><vh>h2</vh></v>
<v t="40323217.20151229164536.127"><vh>p</vh>
<v t="40323217.20151229164536.128"><vh>code</vh></v>
<v t="40323217.20151229164536.129"><vh>code</vh></v>
</v>
<v t="40323217.20151229164536.130"><vh>h2</vh></v>
<v t="40323217.20151229164536.131"><vh>p</vh>
<v t="40323217.20151229164536.132"><vh>code</vh></v>
</v>
<v t="40323217.20151229164536.133"><vh>pre</vh>
<v t="40323217.20151229164536.134"><vh>code</vh></v>
</v>
<v t="40323217.20151229164536.135"><vh>h2 按下 b 或 . 可以 black 畫面</vh></v>
<v t="40323217.20151229164536.136"><vh>p</vh></v>
<v t="40323217.20151229164536.137"><vh>h2 unordered list 頁面</vh>
<v t="40323217.20151229164536.138"><vh>li</vh>
<v t="40323217.20151229164536.139"><vh>a</vh></v>
</v>
<v t="40323217.20151229164536.140"><vh>li</vh>
<v t="40323217.20151229164536.141"><vh>a</vh></v>
</v>
<v t="40323217.20151229164536.142"><vh>li</vh>
<v t="40323217.20151229164536.143"><vh>a</vh></v>
</v>
<v t="40323217.20151229164536.144"><vh>li</vh>
<v t="40323217.20151229164536.145"><vh>a</vh></v>
</v>
<v t="40323217.20151229164536.146"><vh>li</vh></v>
</v>
<v t="40323217.20151229164536.147"><vh>結束單頁</vh></v>
</v>
</v>
<v t="40323217.20151229164536.148"><vh>script</vh></v>
<v t="40323217.20151229164536.149"><vh>script</vh></v>
<v t="40323217.20151229164536.150"><vh>script</vh></v>
</v>
</v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="123.20151208171418.1"></t>
<t tx="123.20151208171418.2">@language python
import os
os.system("pelican pelican/content -o ./ -s pelican/publishconf.py -t ../../theme/pelican-octopress")
g.es("user pelican 執行完畢")</t>
<t tx="123.20151208171418.3"></t>
<t tx="123.20151208171423.1"></t>
<t tx="40323217.20151229164314.1"></t>
<t tx="40323217.20151229164517.1">@language xml
@tabwidth -4
@others
</t>
<t tx="40323217.20151229164517.10">&lt;section&gt;
本日要點
&lt;/section&gt;</t>
<t tx="40323217.20151229164517.11">&lt;section&gt;
&lt;a href="http://continuum.io/downloads"&gt;Anaconda Python 下載&lt;/a&gt;
&lt;/section&gt;</t>
<t tx="40323217.20151229164517.12">&lt;section id="設計的表達方式"&gt;
&lt;section&gt;
設計的表達方式
&lt;/section&gt;
@others
&lt;/section&gt;
</t>
<t tx="40323217.20151229164517.13">&lt;section&gt;
協同模式下的網際雲端內容呈現
&lt;/section&gt;</t>
<t tx="40323217.20151229164517.14">&lt;section&gt;
結論
&lt;/section&gt;</t>
<t tx="40323217.20151229164517.15">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
    </t>
<t tx="40323217.20151229164517.16">&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
 
    </t>
<t tx="40323217.20151229164517.17">&lt;script&gt;
        // Required, even if empty.
        Reveal.initialize({
        });
    &lt;/script&gt;
</t>
<t tx="40323217.20151229164517.2">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;</t>
<t tx="40323217.20151229164517.3">
&lt;head&gt;
@others
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
    &lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;    
    &lt;!--Add support for earlier versions of Internet Explorer --&gt;
    &lt;!--[if lt IE 9]&gt;
    &lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
&lt;/head&gt;
 
</t>
<t tx="40323217.20151229164517.4">
&lt;meta charset="utf-8"&gt;
&lt;title&gt;2015 Fall CADP B Week1&lt;/title&gt;
</t>
<t tx="40323217.20151229164517.5">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="40323217.20151229164517.6">
&lt;!-- Wrap the entire slide show in a div using the "reveal" class. --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229164517.7">
&lt;!-- Wrap all slides in a single "slides" class --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229164517.8">&lt;section id="title page"&gt;
&lt;section&gt;
標題頁面
&lt;/section&gt;
@others
&lt;/section&gt;
</t>
<t tx="40323217.20151229164517.9">&lt;section&gt;
標題頁下的子頁
&lt;/section&gt;</t>
<t tx="40323217.20151229164524.1">@language xml
@tabwidth -4
@others

</t>
<t tx="40323217.20151229164524.10">&lt;section id="fragments"&gt;
        &lt;h1&gt;課程說明&lt;/h1&gt;
    &lt;h3 class="fragment"&gt;課程名稱: 電腦輔助設計實習&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;開放 主動 自學與自評&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;使用 Solvespace 與 Creo 2.0&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;每週都有作業, 由各學員自評分數&lt;/h3&gt;
&lt;/section&gt;
	</t>
<t tx="40323217.20151229164524.100">
&lt;th&gt;Item&lt;/th&gt;
</t>
<t tx="40323217.20151229164524.101">&lt;th&gt;Value&lt;/th&gt;
								</t>
<t tx="40323217.20151229164524.102">&lt;th&gt;Quantity&lt;/th&gt;
							</t>
<t tx="40323217.20151229164524.103">&lt;tbody&gt;
@others
&lt;/tbody&gt;
					</t>
<t tx="40323217.20151229164524.104">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="40323217.20151229164524.105">
&lt;td&gt;Apples&lt;/td&gt;
</t>
<t tx="40323217.20151229164524.106">&lt;td&gt;$1&lt;/td&gt;
								</t>
<t tx="40323217.20151229164524.107">&lt;td&gt;7&lt;/td&gt;
							</t>
<t tx="40323217.20151229164524.108">&lt;tr&gt;
@others
&lt;/tr&gt;
							</t>
<t tx="40323217.20151229164524.109">
&lt;td&gt;Lemonade&lt;/td&gt;
</t>
<t tx="40323217.20151229164524.11">&lt;section id="fragments"&gt;
        &lt;h1&gt;自評說明&lt;/h1&gt;
    &lt;h3 class="fragment"&gt;時效內的 Github 倉儲內容&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;完全開放的學員作業內容&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;彼此間可以互相學習&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;存證內容: Github, copy.com, Vimeo 等&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;要怎麼收穫, 先怎麼栽!&lt;/h3&gt;
&lt;/section&gt;
	</t>
<t tx="40323217.20151229164524.110">&lt;td&gt;$2&lt;/td&gt;
								</t>
<t tx="40323217.20151229164524.111">&lt;td&gt;18&lt;/td&gt;
							</t>
<t tx="40323217.20151229164524.112">&lt;tr&gt;
@others
&lt;/tr&gt;
						</t>
<t tx="40323217.20151229164524.113">
&lt;td&gt;Bread&lt;/td&gt;
</t>
<t tx="40323217.20151229164524.114">&lt;td&gt;$3&lt;/td&gt;
								</t>
<t tx="40323217.20151229164524.115">&lt;td&gt;2&lt;/td&gt;
							</t>
<t tx="40323217.20151229164524.116">&lt;section&gt;
&lt;h2&gt;Clever Quotes&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164524.117">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="40323217.20151229164524.118">
These guys come in two forms, inline: &lt;q cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
&amp;ldquo;The nice thing about standards is that there are so many to choose from&amp;rdquo;&lt;/q&gt; and block:
</t>
<t tx="40323217.20151229164524.119">&lt;blockquote cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
						&amp;ldquo;For years there has been a theory that millions of monkeys typing at random on millions of typewriters would
						reproduce the entire works of Shakespeare. The Internet has proven this theory to be untrue.&amp;rdquo;
&lt;/blockquote&gt;
&lt;/section&gt;
					</t>
<t tx="40323217.20151229164524.12">&lt;section id="fragments"&gt;
    &lt;h2&gt;實體輔助工具&lt;/h2&gt;
    &lt;h3 class="fragment"&gt;電動折疊自行車&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;HP 伺服器&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;3D 印表機零件&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;其他需要採購工具?&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;先模擬分析, 再實際驗證?&lt;/h3&gt;
&lt;/section&gt;
					</t>
<t tx="40323217.20151229164524.120">&lt;section&gt;
&lt;h2&gt;Intergalactic Interconnections&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164524.121">&lt;p&gt;
@others
&lt;/p&gt;
&lt;/section&gt;

				
					</t>
<t tx="40323217.20151229164524.122">
You can link between slides internally,
&lt;a href="#/2/3"&gt;like this&lt;/a&gt;.
</t>
<t tx="40323217.20151229164524.123">&lt;section&gt;
&lt;h2&gt;Speaker View&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164524.124">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="40323217.20151229164524.125">There's a &lt;a href="https://github.com/hakimel/reveal.js#speaker-notes"&gt;speaker view&lt;/a&gt;. It includes a timer, preview of the upcoming slide as well as your speaker notes.</t>
<t tx="40323217.20151229164524.126">&lt;p&gt;
@others
&lt;/p&gt;
    &lt;aside class="notes"&gt;
    Oh hey, these are some notes. They'll be hidden in your presentation, but you can see them if you open the speaker notes window (hit 's' on your keyboard).
    &lt;/aside&gt;
&lt;/section&gt;
					</t>
<t tx="40323217.20151229164524.127">Press the &lt;em&gt;S&lt;/em&gt; key to try it out.</t>
<t tx="40323217.20151229164524.128">&lt;section&gt;
&lt;h2&gt;Export to PDF&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164524.129">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="40323217.20151229164524.13">&lt;section&gt;
@others
&lt;/section&gt;

						</t>
<t tx="40323217.20151229164524.130">Presentations can be &lt;a href="https://github.com/hakimel/reveal.js#pdf-export"&gt;exported to PDF&lt;/a&gt;, here's an example:</t>
<t tx="40323217.20151229164524.131">&lt;iframe src="//www.slideshare.net/slideshow/embed_code/42840540" width="445" height="355" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:3px solid #666; margin-bottom:5px; max-width: 100%;" allowfullscreen&gt; &lt;/iframe&gt;
&lt;/section&gt;
					</t>
<t tx="40323217.20151229164524.132">&lt;section&gt;
&lt;h2&gt;Global State&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164524.133">&lt;p&gt;
@others
&lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="40323217.20151229164524.134">Set &lt;code&gt;data-state="something"&lt;/code&gt; on a slide and </t>
<t tx="40323217.20151229164524.135">&lt;code&gt;"something"&lt;/code&gt;
will be added as a class to the document element when the slide is open. This lets you
apply broader style changes, like switching the page background.
					</t>
<t tx="40323217.20151229164524.136">&lt;section data-state="customevent"&gt;
&lt;h2&gt;State Events&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164524.137">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="40323217.20151229164524.138">
Additionally custom events can be triggered on a per slide basis by binding to the &lt;code&gt;data-state&lt;/code&gt; name.
</t>
<t tx="40323217.20151229164524.139">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;


					</t>
<t tx="40323217.20151229164524.14">&lt;section&gt;
    &lt;h2&gt;Vertical Slides&lt;/h2&gt;
    &lt;p&gt;Slides can be nested inside of each other.&lt;/p&gt;
    &lt;p&gt;
    Use the &lt;em&gt;Space&lt;/em&gt; key to navigate through all slides.
    &lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#" class="navigate-down"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
    &lt;/a&gt;
&lt;/section&gt;</t>
<t tx="40323217.20151229164524.140">&lt;code class="javascript" data-trim contenteditable style="font-size: 18px;"&gt;
Reveal.addEventListener( 'customevent', function() {
	console.log( '"customevent" has fired' );
} );
					&lt;/code&gt;</t>
<t tx="40323217.20151229164524.141">&lt;section&gt;
&lt;h2&gt;Take a Moment&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164524.142">&lt;p&gt;
Press B or . on your keyboard to pause the presentation. This is helpful when you're on stage and want to take distracting slides off the screen.
&lt;/p&gt;
&lt;/section&gt;

				
					</t>
<t tx="40323217.20151229164524.143">&lt;section&gt;
&lt;h2&gt;Much more&lt;/h2&gt;
    &lt;ul&gt;
    @others
    &lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="40323217.20151229164524.144">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="40323217.20151229164524.145">&lt;a href="https://github.com/hakimel/reveal.js#auto-sliding"&gt;Auto-progression&lt;/a&gt;</t>
<t tx="40323217.20151229164524.146">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="40323217.20151229164524.147">&lt;a href="https://github.com/hakimel/reveal.js#parallax-background"&gt;Parallax backgrounds&lt;/a&gt;</t>
<t tx="40323217.20151229164524.148">&lt;li&gt;
@others
&lt;/li&gt;
					</t>
<t tx="40323217.20151229164524.149">&lt;a href="https://github.com/hakimel/reveal.js#keyboard-bindings"&gt;Custom keyboard bindings&lt;/a&gt;</t>
<t tx="40323217.20151229164524.15">&lt;section&gt;
    &lt;h2&gt;Basement Level 1&lt;/h2&gt;
    &lt;p&gt;Nested slides are useful for adding additional detail underneath a high level horizontal slide.&lt;/p&gt;
&lt;/section&gt;
						</t>
<t tx="40323217.20151229164524.150">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="40323217.20151229164524.151">&lt;a href="https://github.com/hakimel/reveal.js#api"&gt;Extensive JavaScript API&lt;/a&gt;</t>
<t tx="40323217.20151229164524.152">&lt;li&gt;Right-to-left support&lt;/li&gt;
</t>
<t tx="40323217.20151229164524.153">&lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;section&gt;
					</t>
<t tx="40323217.20151229164524.154">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
		</t>
<t tx="40323217.20151229164524.155">&lt;script src="js/reveal.js"&gt;&lt;/script&gt;

		</t>
<t tx="40323217.20151229164524.156">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="40323217.20151229164524.16">&lt;section&gt;
    &lt;h2&gt;Basement Level 2&lt;/h2&gt;
    &lt;p&gt;That's it, time to go back up.&lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#/2"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="transform: rotate(180deg); -webkit-transform: rotate(180deg);"&gt;
    &lt;/a&gt;
&lt;/section&gt;
						</t>
<t tx="40323217.20151229164524.17">&lt;section&gt;
    &lt;h2&gt;Pretty Code&lt;/h2&gt;
    @others
&lt;/section&gt;
					</t>
<t tx="40323217.20151229164524.18">&lt;pre&gt;
    &lt;code data-trim contenteditable&gt;
    @others
    &lt;/code&gt;
&lt;/pre&gt;
					</t>
<t tx="40323217.20151229164524.19">function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
</t>
<t tx="40323217.20151229164524.2">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;</t>
<t tx="40323217.20151229164524.20">&lt;p&gt;
Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.
&lt;/p&gt;



					</t>
<t tx="40323217.20151229164524.21">&lt;section&gt;
    &lt;h2&gt;Slides&lt;/h2&gt;
    &lt;p&gt;
    Not a coder? Not a problem. There's a fully-featured visual editor for authoring these, try it out at &lt;a href="http://slides.com" target="_blank"&gt;http://slides.com&lt;/a&gt;.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="40323217.20151229164524.22">&lt;section&gt;
&lt;h1&gt;嵌入 Vimeo 影片&lt;/h1&gt;
&lt;iframe src="https://player.vimeo.com/video/137724068" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt; &lt;p&gt;&lt;a href="https://vimeo.com/137724068"&gt;Welcome Speech&lt;/a&gt; from &lt;a href="https://vimeo.com/user24079973"&gt;虎尾科大機械設計工程系 KMOL&lt;/a&gt; on &lt;a href="https://vimeo.com"&gt;Vimeo&lt;/a&gt;.&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="40323217.20151229164524.23">&lt;section&gt;
    &lt;h2&gt;Point of View&lt;/h2&gt;
    &lt;p&gt;
    Press &lt;strong&gt;ESC&lt;/strong&gt; to enter the slide overview.
    &lt;/p&gt;
    &lt;p&gt;
    Hold down alt and click on any element to zoom in on it using &lt;a href="http://lab.hakim.se/zoom-js"&gt;zoom.js&lt;/a&gt;. Alt + click anywhere to zoom back out.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="40323217.20151229164524.24">&lt;section&gt;
    &lt;h2&gt;Touch Optimized&lt;/h2&gt;
    &lt;p&gt;
    Presentations look great on touch devices, like mobile phones and tablets. Simply swipe through your slides.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="40323217.20151229164524.25">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
        ## Markdown support
        
        Write content using inline or external Markdown.
        Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
        
            ```
            &lt;section data-markdown&gt;
              ## Markdown support
            
              Write content using inline or external Markdown.
              Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
            &lt;/section&gt;
            ```
    &lt;/script&gt;
&lt;/section&gt;


						</t>
<t tx="40323217.20151229164524.26">&lt;section&gt;
    @others
&lt;/section&gt;

						</t>
<t tx="40323217.20151229164524.27">&lt;section id="fragments"&gt;
&lt;h2&gt;Fragments&lt;/h2&gt;
&lt;p&gt;Hit the next arrow...&lt;/p&gt;
&lt;p class="fragment"&gt;... to step through ...&lt;/p&gt;
&lt;p&gt;
    &lt;span class="fragment"&gt;... a&lt;/span&gt; 
    &lt;span class="fragment"&gt;fragmented&lt;/span&gt;
    &lt;span class="fragment"&gt;slide.&lt;/span&gt;
&lt;/p&gt;

&lt;aside class="notes"&gt;
This slide has fragments which are also stepped through in the notes window.
&lt;/aside&gt;
&lt;/section&gt;</t>
<t tx="40323217.20151229164524.28">&lt;section&gt;
@others
&lt;/section&gt;


						</t>
<t tx="40323217.20151229164524.29">&lt;h2&gt;Fragment Styles&lt;/h2&gt;</t>
<t tx="40323217.20151229164524.3">&lt;head&gt;
@others
&lt;/head&gt;

</t>
<t tx="40323217.20151229164524.30">&lt;p&gt;There's different types of fragments, like:&lt;/p&gt;
						</t>
<t tx="40323217.20151229164524.31">&lt;p class="fragment grow"&gt;grow&lt;/p&gt;
						</t>
<t tx="40323217.20151229164524.32">&lt;p class="fragment shrink"&gt;shrink&lt;/p&gt;
						</t>
<t tx="40323217.20151229164524.33">&lt;p class="fragment fade-out"&gt;fade-out&lt;/p&gt;
						</t>
<t tx="40323217.20151229164524.34">&lt;p class="fragment current-visible"&gt;current-visible&lt;/p&gt;
						</t>
<t tx="40323217.20151229164524.35">&lt;p class="fragment highlight-red"&gt;highlight-red&lt;/p&gt;
						</t>
<t tx="40323217.20151229164524.36">&lt;p class="fragment highlight-blue"&gt;highlight-blue&lt;/p&gt;


				
					</t>
<t tx="40323217.20151229164524.37">&lt;section id="transitions"&gt;
&lt;h2&gt;Transition Styles&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164524.38">&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;


					</t>
<t tx="40323217.20151229164524.39">
You can select from different transitions, like: &lt;br&gt;
&lt;a href="?transition=none#/transitions"&gt;None&lt;/a&gt; -
</t>
<t tx="40323217.20151229164524.4">&lt;meta charset="utf-8"&gt;

&lt;title&gt;2015 Fall 電腦輔助設計實習 甲班&lt;/title&gt;

</t>
<t tx="40323217.20151229164524.40">&lt;a href="?transition=fade#/transitions"&gt;Fade&lt;/a&gt; -
						</t>
<t tx="40323217.20151229164524.41">&lt;a href="?transition=slide#/transitions"&gt;Slide&lt;/a&gt; -
						</t>
<t tx="40323217.20151229164524.42">&lt;a href="?transition=convex#/transitions"&gt;Convex&lt;/a&gt; -
						</t>
<t tx="40323217.20151229164524.43">&lt;a href="?transition=concave#/transitions"&gt;Concave&lt;/a&gt; -
						</t>
<t tx="40323217.20151229164524.44">&lt;a href="?transition=zoom#/transitions"&gt;Zoom&lt;/a&gt;
					</t>
<t tx="40323217.20151229164524.45">&lt;section id="themes"&gt;
&lt;h2&gt;Themes&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164524.46">&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;section data-background="#dddddd"&gt;
						</t>
<t tx="40323217.20151229164524.47">
reveal.js comes with a few themes built in: &lt;br&gt;
&lt;!-- Hacks to swap themes after the page has loaded. Not flexible and only intended for the reveal.js demo deck. --&gt;
&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/black.css'); return false;"&gt;Black (default)&lt;/a&gt; -
</t>
<t tx="40323217.20151229164524.48">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/white.css'); return false;"&gt;White&lt;/a&gt; -
						</t>
<t tx="40323217.20151229164524.49">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/league.css'); return false;"&gt;League&lt;/a&gt; -
						</t>
<t tx="40323217.20151229164524.5">&lt;meta name="description" content="2015Fall CADP"&gt;
&lt;meta name="author" content="KMOL"&gt;
&lt;meta name="apple-mobile-web-app-capable" content="yes" /&gt;
&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" /&gt;
		</t>
<t tx="40323217.20151229164524.50">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/sky.css'); return false;"&gt;Sky&lt;/a&gt; -
						</t>
<t tx="40323217.20151229164524.51">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/beige.css'); return false;"&gt;Beige&lt;/a&gt; -
						</t>
<t tx="40323217.20151229164524.52">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/simple.css'); return false;"&gt;Simple&lt;/a&gt; </t>
<t tx="40323217.20151229164524.53">&lt;br&gt;
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/serif.css'); return false;"&gt;Serif&lt;/a&gt; -
						</t>
<t tx="40323217.20151229164524.54">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/blood.css'); return false;"&gt;Blood&lt;/a&gt; -
						</t>
<t tx="40323217.20151229164524.55">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/night.css'); return false;"&gt;Night&lt;/a&gt; -
						</t>
<t tx="40323217.20151229164524.56">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/moon.css'); return false;"&gt;Moon&lt;/a&gt; -
						</t>
<t tx="40323217.20151229164524.57">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/solarized.css'); return false;"&gt;Solarized&lt;/a&gt;
					</t>
<t tx="40323217.20151229164524.58">&lt;h2&gt;Slide Backgrounds&lt;/h2&gt;
						</t>
<t tx="40323217.20151229164524.59">&lt;p&gt;
@others
&lt;/p&gt;
						</t>
<t tx="40323217.20151229164524.6">&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui"&gt;

    &lt;link rel="stylesheet" href="css/reveal.css"&gt;
    &lt;link rel="stylesheet" href="css/theme/black.css" id="theme"&gt;

    &lt;!-- Code syntax highlighting --&gt;
    &lt;link rel="stylesheet" href="lib/css/zenburn.css"&gt;

    &lt;!-- Printing and PDF exports --&gt;
    &lt;script&gt;
        var link = document.createElement( 'link' );
        link.rel = 'stylesheet';
        link.type = 'text/css';
        link.href = window.location.search.match( /print-pdf/gi ) ? 'css/print/pdf.css' : 'css/print/paper.css';
        document.getElementsByTagName( 'head' )[0].appendChild( link );
    &lt;/script&gt;

    &lt;!--[if lt IE 9]&gt;
    &lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
	</t>
<t tx="40323217.20151229164524.60">
Set &lt;code&gt;data-background="#dddddd"&lt;/code&gt; on a slide to change the background color. All CSS color formats are supported.
</t>
<t tx="40323217.20151229164524.61">&lt;a href="#" class="navigate-down"&gt;
							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
						&lt;/a&gt;
					&lt;/section&gt;
					&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png"&gt;
						</t>
<t tx="40323217.20151229164524.62">&lt;h2&gt;Image Backgrounds&lt;/h2&gt;
						</t>
<t tx="40323217.20151229164524.63">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;
						</t>
<t tx="40323217.20151229164524.64">&lt;code&gt;&amp;lt;section data-background="image.png"&amp;gt;&lt;/code&gt;</t>
<t tx="40323217.20151229164524.65">&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png" data-background-repeat="repeat" data-background-size="100px"&gt;
&lt;h2&gt;Tiled Backgrounds&lt;/h2&gt;
						</t>
<t tx="40323217.20151229164524.66">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;
&lt;section data-background-video="https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.mp4,https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.webm" data-background-color="#000000"&gt;
						</t>
<t tx="40323217.20151229164524.67">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background="image.png" data-background-repeat="repeat" data-background-size="100px"&amp;gt;
&lt;/code&gt;</t>
<t tx="40323217.20151229164524.68">&lt;div style="background-color: rgba(0, 0, 0, 0.9); color: #fff; padding: 20px;"&gt;
@others
&lt;/div&gt;
&lt;/section&gt;

						</t>
<t tx="40323217.20151229164524.69">&lt;section data-background="http://i.giphy.com/90F8aUepslB84.gif"&gt;
&lt;h2&gt;Video Backgrounds&lt;/h2&gt;
</t>
<t tx="40323217.20151229164524.7">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="40323217.20151229164524.70">&lt;pre&gt;
@others
&lt;/pre&gt;
						</t>
<t tx="40323217.20151229164524.71">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background-video="video.mp4,video.webm"&amp;gt;&lt;/code&gt;</t>
<t tx="40323217.20151229164524.72">&lt;h2&gt;... and GIFs!&lt;/h2&gt;
&lt;/section&gt;
&lt;/section&gt;
					</t>
<t tx="40323217.20151229164524.73">&lt;section data-transition="slide" data-background="#4d7e65" data-background-transition="zoom"&gt;
&lt;h2&gt;Background Transitions&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164524.74">&lt;p&gt;
						Different background transitions are available via the backgroundTransition option. This one's called "zoom".
					&lt;/p&gt;
					</t>
<t tx="40323217.20151229164524.75">&lt;pre&gt;
@others
&lt;/pre&gt;
				&lt;/section&gt;

				&lt;section data-transition="slide" data-background="#b5533c" data-background-transition="zoom"&gt;
					</t>
<t tx="40323217.20151229164524.76">&lt;code&gt;Reveal.configure({ backgroundTransition: 'zoom' })&lt;/code&gt;</t>
<t tx="40323217.20151229164524.77">&lt;h2&gt;Background Transitions&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164524.78">&lt;p&gt;
You can override background transitions per-slide.
&lt;/p&gt;
					</t>
<t tx="40323217.20151229164524.79">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;


					</t>
<t tx="40323217.20151229164524.8">&lt;div class="reveal"&gt;
@others
&lt;/div&gt;

</t>
<t tx="40323217.20151229164524.80">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background-transition="zoom"&amp;gt;&lt;/code&gt;</t>
<t tx="40323217.20151229164524.81">&lt;section&gt;
    &lt;h2&gt;Pretty Code&lt;/h2&gt;
    @others
&lt;/section&gt;
					</t>
<t tx="40323217.20151229164524.82">&lt;pre&gt;
    &lt;code data-trim contenteditable&gt;
    @others
    &lt;/code&gt;
&lt;/pre&gt;
					</t>
<t tx="40323217.20151229164524.83">function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
</t>
<t tx="40323217.20151229164524.84">&lt;p&gt;
Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.
&lt;/p&gt;



					</t>
<t tx="40323217.20151229164524.85">&lt;section&gt;
&lt;h2&gt;Marvelous List&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164524.86">&lt;ul&gt;
@others
&lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="40323217.20151229164524.87">
&lt;li&gt;No order here&lt;/li&gt;
</t>
<t tx="40323217.20151229164524.88">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="40323217.20151229164524.89">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="40323217.20151229164524.9">&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;

</t>
<t tx="40323217.20151229164524.90">&lt;li&gt;Or here&lt;/li&gt;
					</t>
<t tx="40323217.20151229164524.91">&lt;section&gt;
&lt;h2&gt;Fantastic Ordered List&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164524.92">&lt;ol&gt;
@others
&lt;/ol&gt;
&lt;/section&gt;

					</t>
<t tx="40323217.20151229164524.93">
&lt;li&gt;One is smaller than...&lt;/li&gt;
</t>
<t tx="40323217.20151229164524.94">&lt;li&gt;Two is smaller than...&lt;/li&gt;
						</t>
<t tx="40323217.20151229164524.95">&lt;li&gt;Three!&lt;/li&gt;
					</t>
<t tx="40323217.20151229164524.96">&lt;section&gt;
&lt;h2&gt;Tabular Tables&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164524.97">&lt;table&gt;
@others
&lt;/table&gt;
&lt;/section&gt;


					</t>
<t tx="40323217.20151229164524.98">&lt;thead&gt;
@others
&lt;/thead&gt;
</t>
<t tx="40323217.20151229164524.99">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="40323217.20151229164529.1">@language xml
@tabwidth -4
@others

</t>
<t tx="40323217.20151229164529.10">&lt;section&gt;
    &lt;h1&gt;Git 操作&lt;/h1&gt;
    &lt;p&gt;git clone&lt;/p&gt;
    &lt;p&gt;git config --global user.name&lt;/p&gt;
    &lt;p&gt;git config --global user.email&lt;/p&gt;
    &lt;p&gt;git add -A&lt;/p&gt;
    &lt;p&gt;git commit -m&lt;/p&gt;
    &lt;p&gt;git push&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="40323217.20151229164529.11">&lt;section&gt;
    &lt;h1&gt;Jupyter 操作&lt;/h1&gt;
    &lt;p&gt;啟動&lt;/p&gt;
    &lt;p&gt;基本執行&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="40323217.20151229164529.12">&lt;section&gt;
    &lt;h1&gt;結論&lt;/h1&gt;
    &lt;p&gt;自主開放學習&lt;/p&gt;
    &lt;p&gt;線上教材&lt;/p&gt;
    &lt;p&gt;影音教材&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="40323217.20151229164529.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	</t>
<t tx="40323217.20151229164529.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="40323217.20151229164529.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;2015CP W1&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
&lt;/html&gt;</t>
<t tx="40323217.20151229164529.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="40323217.20151229164529.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229164529.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229164529.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;計算機程式&lt;/h1&gt;
    &lt;p&gt;第1週教學內容&lt;/p&gt;		
&lt;/section&gt;
	</t>
<t tx="40323217.20151229164529.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;課程規劃&lt;/h1&gt;
    &lt;p&gt;教科書&lt;/p&gt;
    &lt;p&gt;請參考 &lt;a href="http://openbookproject.net/thinkcs/python/english3e/"&gt;http://openbookproject.net/thinkcs/python/english3e/&lt;/a&gt;
&lt;/section&gt;
				</t>
<t tx="40323217.20151229164529.9">&lt;section&gt;
    &lt;h1&gt;作業規劃&lt;/h1&gt;
    &lt;p&gt;影片內容&lt;/p&gt;
    &lt;a href="https://www.youtube.com/watch?v=9uq3w6JJS00"&gt;Zero to hero with Python&lt;/a&gt;
&lt;/section&gt;
				</t>
<t tx="40323217.20151229164536.1">@language xml
@tabwidth -4
@others

</t>
<t tx="40323217.20151229164536.10">&lt;section&gt;
        &lt;h1&gt;Reveal.js 使用說明&lt;/h1&gt;
    &lt;h3&gt;The HTML Presentation Framework 框架&lt;/h3&gt;
    &lt;p&gt;
    &lt;small&gt;
    Created by &lt;a href="http://hakim.se"&gt;Hakim El Hattab&lt;/a&gt; / 
    &lt;a href="http://twitter.com/hakimel"&gt;@hakimel&lt;/a&gt;
    &lt;/small&gt;
    &lt;/p&gt;
&lt;/section&gt;
	</t>
<t tx="40323217.20151229164536.100">&lt;td&gt;$1&lt;/td&gt;
								</t>
<t tx="40323217.20151229164536.101">&lt;td&gt;7&lt;/td&gt;
							</t>
<t tx="40323217.20151229164536.102">&lt;tr&gt;
@others
&lt;/tr&gt;
							</t>
<t tx="40323217.20151229164536.103">
&lt;td&gt;Lemonade&lt;/td&gt;
</t>
<t tx="40323217.20151229164536.104">&lt;td&gt;$2&lt;/td&gt;
								</t>
<t tx="40323217.20151229164536.105">&lt;td&gt;18&lt;/td&gt;
							</t>
<t tx="40323217.20151229164536.106">&lt;tr&gt;
@others
&lt;/tr&gt;
						</t>
<t tx="40323217.20151229164536.107">
&lt;td&gt;Bread&lt;/td&gt;
</t>
<t tx="40323217.20151229164536.108">&lt;td&gt;$3&lt;/td&gt;
								</t>
<t tx="40323217.20151229164536.109">&lt;td&gt;2&lt;/td&gt;
							</t>
<t tx="40323217.20151229164536.11">&lt;section&gt;
    &lt;h2&gt;Hello There&lt;/h2&gt;
    &lt;p&gt;
reveal.js enables you to create beautiful interactive slide decks using HTML. This presentation will show you examples of what it can do.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="40323217.20151229164536.110">&lt;section&gt;
&lt;h2&gt;Clever Quotes&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164536.111">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="40323217.20151229164536.112">
These guys come in two forms, inline: &lt;q cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
&amp;ldquo;The nice thing about standards is that there are so many to choose from&amp;rdquo;&lt;/q&gt; and block:
</t>
<t tx="40323217.20151229164536.113">&lt;blockquote cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
						&amp;ldquo;For years there has been a theory that millions of monkeys typing at random on millions of typewriters would
						reproduce the entire works of Shakespeare. The Internet has proven this theory to be untrue.&amp;rdquo;
&lt;/blockquote&gt;
&lt;/section&gt;
					</t>
<t tx="40323217.20151229164536.114">&lt;section&gt;
&lt;h2&gt;Intergalactic Interconnections&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164536.115">&lt;p&gt;
@others
&lt;/p&gt;
&lt;/section&gt;

				
					</t>
<t tx="40323217.20151229164536.116">
You can link between slides internally,
&lt;a href="#/2/3"&gt;like this&lt;/a&gt;.
</t>
<t tx="40323217.20151229164536.117">&lt;section&gt;
&lt;h2&gt;Speaker View&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164536.118">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="40323217.20151229164536.119">There's a &lt;a href="https://github.com/hakimel/reveal.js#speaker-notes"&gt;speaker view&lt;/a&gt;. It includes a timer, preview of the upcoming slide as well as your speaker notes.</t>
<t tx="40323217.20151229164536.12">&lt;section&gt;
@others
&lt;/section&gt;

						</t>
<t tx="40323217.20151229164536.120">&lt;p&gt;
@others
&lt;/p&gt;
    &lt;aside class="notes"&gt;
    Oh hey, these are some notes. They'll be hidden in your presentation, but you can see them if you open the speaker notes window (hit 's' on your keyboard).
    &lt;/aside&gt;
&lt;/section&gt;
					</t>
<t tx="40323217.20151229164536.121">Press the &lt;em&gt;S&lt;/em&gt; key to try it out.</t>
<t tx="40323217.20151229164536.122">&lt;section&gt;
&lt;h2&gt;Export to PDF&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164536.123">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="40323217.20151229164536.124">Presentations can be &lt;a href="https://github.com/hakimel/reveal.js#pdf-export"&gt;exported to PDF&lt;/a&gt;, here's an example:</t>
<t tx="40323217.20151229164536.125">&lt;iframe src="//www.slideshare.net/slideshow/embed_code/42840540" width="445" height="355" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:3px solid #666; margin-bottom:5px; max-width: 100%;" allowfullscreen&gt; &lt;/iframe&gt;
&lt;/section&gt;
					</t>
<t tx="40323217.20151229164536.126">&lt;section&gt;
&lt;h2&gt;Global State&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164536.127">&lt;p&gt;
@others
&lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="40323217.20151229164536.128">Set &lt;code&gt;data-state="something"&lt;/code&gt; on a slide and </t>
<t tx="40323217.20151229164536.129">&lt;code&gt;"something"&lt;/code&gt;
will be added as a class to the document element when the slide is open. This lets you
apply broader style changes, like switching the page background.
					</t>
<t tx="40323217.20151229164536.13">&lt;section&gt;
    &lt;h2&gt;Vertical Slides&lt;/h2&gt;
    &lt;p&gt;Slides can be nested inside of each other.&lt;/p&gt;
    &lt;p&gt;
    Use the &lt;em&gt;Space&lt;/em&gt; key to navigate through all slides.
    &lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#" class="navigate-down"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
    &lt;/a&gt;
&lt;/section&gt;</t>
<t tx="40323217.20151229164536.130">&lt;section data-state="customevent"&gt;
&lt;h2&gt;State Events&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164536.131">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="40323217.20151229164536.132">
Additionally custom events can be triggered on a per slide basis by binding to the &lt;code&gt;data-state&lt;/code&gt; name.
</t>
<t tx="40323217.20151229164536.133">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;


					</t>
<t tx="40323217.20151229164536.134">&lt;code class="javascript" data-trim contenteditable style="font-size: 18px;"&gt;
Reveal.addEventListener( 'customevent', function() {
	console.log( '"customevent" has fired' );
} );
					&lt;/code&gt;</t>
<t tx="40323217.20151229164536.135">&lt;section&gt;
&lt;h2&gt;Take a Moment&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164536.136">&lt;p&gt;
Press B or . on your keyboard to pause the presentation. This is helpful when you're on stage and want to take distracting slides off the screen.
&lt;/p&gt;
&lt;/section&gt;

				
					</t>
<t tx="40323217.20151229164536.137">&lt;section&gt;
&lt;h2&gt;Much more&lt;/h2&gt;
    &lt;ul&gt;
    @others
    &lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="40323217.20151229164536.138">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="40323217.20151229164536.139">&lt;a href="https://github.com/hakimel/reveal.js#auto-sliding"&gt;Auto-progression&lt;/a&gt;</t>
<t tx="40323217.20151229164536.14">&lt;section&gt;
    &lt;h2&gt;Basement Level 1&lt;/h2&gt;
    &lt;p&gt;Nested slides are useful for adding additional detail underneath a high level horizontal slide.&lt;/p&gt;
&lt;/section&gt;
						</t>
<t tx="40323217.20151229164536.140">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="40323217.20151229164536.141">&lt;a href="https://github.com/hakimel/reveal.js#parallax-background"&gt;Parallax backgrounds&lt;/a&gt;</t>
<t tx="40323217.20151229164536.142">&lt;li&gt;
@others
&lt;/li&gt;
					</t>
<t tx="40323217.20151229164536.143">&lt;a href="https://github.com/hakimel/reveal.js#keyboard-bindings"&gt;Custom keyboard bindings&lt;/a&gt;</t>
<t tx="40323217.20151229164536.144">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="40323217.20151229164536.145">&lt;a href="https://github.com/hakimel/reveal.js#api"&gt;Extensive JavaScript API&lt;/a&gt;</t>
<t tx="40323217.20151229164536.146">&lt;li&gt;Right-to-left support&lt;/li&gt;
</t>
<t tx="40323217.20151229164536.147">&lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;section&gt;
					</t>
<t tx="40323217.20151229164536.148">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
		</t>
<t tx="40323217.20151229164536.149">&lt;script src="js/reveal.js"&gt;&lt;/script&gt;

		</t>
<t tx="40323217.20151229164536.15">&lt;section&gt;
    &lt;h2&gt;Basement Level 2&lt;/h2&gt;
    &lt;p&gt;That's it, time to go back up.&lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#/2"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="transform: rotate(180deg); -webkit-transform: rotate(180deg);"&gt;
    &lt;/a&gt;
&lt;/section&gt;
						</t>
<t tx="40323217.20151229164536.150">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="40323217.20151229164536.16">&lt;section&gt;
    &lt;h2&gt;Slides&lt;/h2&gt;
    &lt;p&gt;
    Not a coder? Not a problem. There's a fully-featured visual editor for authoring these, try it out at &lt;a href="http://slides.com" target="_blank"&gt;http://slides.com&lt;/a&gt;.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="40323217.20151229164536.17">&lt;section&gt;
    &lt;h2&gt;Point of View&lt;/h2&gt;
    &lt;p&gt;
    Press &lt;strong&gt;ESC&lt;/strong&gt; to enter the slide overview.
    &lt;/p&gt;
    &lt;p&gt;
    Hold down alt and click on any element to zoom in on it using &lt;a href="http://lab.hakim.se/zoom-js"&gt;zoom.js&lt;/a&gt;. Alt + click anywhere to zoom back out.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="40323217.20151229164536.18">&lt;section&gt;
    &lt;h2&gt;Touch Optimized&lt;/h2&gt;
    &lt;p&gt;
    Presentations look great on touch devices, like mobile phones and tablets. Simply swipe through your slides.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="40323217.20151229164536.19">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
        ## Markdown support
        
        Write content using inline or external Markdown.
        Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
        
            ```
            &lt;section data-markdown&gt;
              ## Markdown support
            
              Write content using inline or external Markdown.
              Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
            &lt;/section&gt;
            ```
    &lt;/script&gt;
&lt;/section&gt;


						</t>
<t tx="40323217.20151229164536.2">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;</t>
<t tx="40323217.20151229164536.20">&lt;section&gt;
    @others
&lt;/section&gt;

						</t>
<t tx="40323217.20151229164536.21">&lt;section id="fragments"&gt;
&lt;h2&gt;Fragments&lt;/h2&gt;
&lt;p&gt;Hit the next arrow...&lt;/p&gt;
&lt;p class="fragment"&gt;... to step through ...&lt;/p&gt;
&lt;p&gt;
    &lt;span class="fragment"&gt;... a&lt;/span&gt; 
    &lt;span class="fragment"&gt;fragmented&lt;/span&gt;
    &lt;span class="fragment"&gt;slide.&lt;/span&gt;
&lt;/p&gt;

&lt;aside class="notes"&gt;
This slide has fragments which are also stepped through in the notes window.
&lt;/aside&gt;
&lt;/section&gt;</t>
<t tx="40323217.20151229164536.22">&lt;section&gt;
@others
&lt;/section&gt;


						</t>
<t tx="40323217.20151229164536.23">&lt;h2&gt;Fragment Styles&lt;/h2&gt;</t>
<t tx="40323217.20151229164536.24">&lt;p&gt;There's different types of fragments, like:&lt;/p&gt;
						</t>
<t tx="40323217.20151229164536.25">&lt;p class="fragment grow"&gt;grow&lt;/p&gt;
						</t>
<t tx="40323217.20151229164536.26">&lt;p class="fragment shrink"&gt;shrink&lt;/p&gt;
						</t>
<t tx="40323217.20151229164536.27">&lt;p class="fragment fade-out"&gt;fade-out&lt;/p&gt;
						</t>
<t tx="40323217.20151229164536.28">&lt;p class="fragment current-visible"&gt;current-visible&lt;/p&gt;
						</t>
<t tx="40323217.20151229164536.29">&lt;p class="fragment highlight-red"&gt;highlight-red&lt;/p&gt;
						</t>
<t tx="40323217.20151229164536.3">&lt;head&gt;
@others
&lt;/head&gt;

</t>
<t tx="40323217.20151229164536.30">&lt;p class="fragment highlight-blue"&gt;highlight-blue&lt;/p&gt;


				
					</t>
<t tx="40323217.20151229164536.31">&lt;section id="transitions"&gt;
&lt;h2&gt;Transition Styles&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164536.32">&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;


					</t>
<t tx="40323217.20151229164536.33">
You can select from different transitions, like: &lt;br&gt;
&lt;a href="?transition=none#/transitions"&gt;None&lt;/a&gt; -
</t>
<t tx="40323217.20151229164536.34">&lt;a href="?transition=fade#/transitions"&gt;Fade&lt;/a&gt; -
						</t>
<t tx="40323217.20151229164536.35">&lt;a href="?transition=slide#/transitions"&gt;Slide&lt;/a&gt; -
						</t>
<t tx="40323217.20151229164536.36">&lt;a href="?transition=convex#/transitions"&gt;Convex&lt;/a&gt; -
						</t>
<t tx="40323217.20151229164536.37">&lt;a href="?transition=concave#/transitions"&gt;Concave&lt;/a&gt; -
						</t>
<t tx="40323217.20151229164536.38">&lt;a href="?transition=zoom#/transitions"&gt;Zoom&lt;/a&gt;
					</t>
<t tx="40323217.20151229164536.39">&lt;section id="themes"&gt;
&lt;h2&gt;Themes&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164536.4">&lt;meta charset="utf-8"&gt;

&lt;title&gt;reveal.js - The HTML Presentation Framework&lt;/title&gt;

</t>
<t tx="40323217.20151229164536.40">&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;section data-background="#dddddd"&gt;
						</t>
<t tx="40323217.20151229164536.41">
reveal.js comes with a few themes built in: &lt;br&gt;
&lt;!-- Hacks to swap themes after the page has loaded. Not flexible and only intended for the reveal.js demo deck. --&gt;
&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/black.css'); return false;"&gt;Black (default)&lt;/a&gt; -
</t>
<t tx="40323217.20151229164536.42">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/white.css'); return false;"&gt;White&lt;/a&gt; -
						</t>
<t tx="40323217.20151229164536.43">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/league.css'); return false;"&gt;League&lt;/a&gt; -
						</t>
<t tx="40323217.20151229164536.44">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/sky.css'); return false;"&gt;Sky&lt;/a&gt; -
						</t>
<t tx="40323217.20151229164536.45">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/beige.css'); return false;"&gt;Beige&lt;/a&gt; -
						</t>
<t tx="40323217.20151229164536.46">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/simple.css'); return false;"&gt;Simple&lt;/a&gt; </t>
<t tx="40323217.20151229164536.47">&lt;br&gt;
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/serif.css'); return false;"&gt;Serif&lt;/a&gt; -
						</t>
<t tx="40323217.20151229164536.48">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/blood.css'); return false;"&gt;Blood&lt;/a&gt; -
						</t>
<t tx="40323217.20151229164536.49">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/night.css'); return false;"&gt;Night&lt;/a&gt; -
						</t>
<t tx="40323217.20151229164536.5">&lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
&lt;meta name="author" content="Hakim El Hattab"&gt;
&lt;meta name="apple-mobile-web-app-capable" content="yes" /&gt;
&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" /&gt;
		</t>
<t tx="40323217.20151229164536.50">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/moon.css'); return false;"&gt;Moon&lt;/a&gt; -
						</t>
<t tx="40323217.20151229164536.51">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/solarized.css'); return false;"&gt;Solarized&lt;/a&gt;
					</t>
<t tx="40323217.20151229164536.52">&lt;h2&gt;Slide Backgrounds&lt;/h2&gt;
						</t>
<t tx="40323217.20151229164536.53">&lt;p&gt;
@others
&lt;/p&gt;
						</t>
<t tx="40323217.20151229164536.54">
Set &lt;code&gt;data-background="#dddddd"&lt;/code&gt; on a slide to change the background color. All CSS color formats are supported.
</t>
<t tx="40323217.20151229164536.55">&lt;a href="#" class="navigate-down"&gt;
							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
						&lt;/a&gt;
					&lt;/section&gt;
					&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png"&gt;
						</t>
<t tx="40323217.20151229164536.56">&lt;h2&gt;Image Backgrounds&lt;/h2&gt;
						</t>
<t tx="40323217.20151229164536.57">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;
						</t>
<t tx="40323217.20151229164536.58">&lt;code&gt;&amp;lt;section data-background="image.png"&amp;gt;&lt;/code&gt;</t>
<t tx="40323217.20151229164536.59">&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png" data-background-repeat="repeat" data-background-size="100px"&gt;
&lt;h2&gt;Tiled Backgrounds&lt;/h2&gt;
						</t>
<t tx="40323217.20151229164536.6">&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui"&gt;

    &lt;link rel="stylesheet" href="css/reveal.css"&gt;
    &lt;link rel="stylesheet" href="css/theme/black.css" id="theme"&gt;

    &lt;!-- Code syntax highlighting --&gt;
    &lt;link rel="stylesheet" href="lib/css/zenburn.css"&gt;

    &lt;!-- Printing and PDF exports --&gt;
    &lt;script&gt;
        var link = document.createElement( 'link' );
        link.rel = 'stylesheet';
        link.type = 'text/css';
        link.href = window.location.search.match( /print-pdf/gi ) ? 'css/print/pdf.css' : 'css/print/paper.css';
        document.getElementsByTagName( 'head' )[0].appendChild( link );
    &lt;/script&gt;

    &lt;!--[if lt IE 9]&gt;
    &lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
	</t>
<t tx="40323217.20151229164536.60">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;
&lt;section data-background-video="https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.mp4,https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.webm" data-background-color="#000000"&gt;
						</t>
<t tx="40323217.20151229164536.61">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background="image.png" data-background-repeat="repeat" data-background-size="100px"&amp;gt;
&lt;/code&gt;</t>
<t tx="40323217.20151229164536.62">&lt;div style="background-color: rgba(0, 0, 0, 0.9); color: #fff; padding: 20px;"&gt;
@others
&lt;/div&gt;
&lt;/section&gt;

						</t>
<t tx="40323217.20151229164536.63">&lt;section data-background="http://i.giphy.com/90F8aUepslB84.gif"&gt;
&lt;h2&gt;Video Backgrounds&lt;/h2&gt;
</t>
<t tx="40323217.20151229164536.64">&lt;pre&gt;
@others
&lt;/pre&gt;
						</t>
<t tx="40323217.20151229164536.65">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background-video="video.mp4,video.webm"&amp;gt;&lt;/code&gt;</t>
<t tx="40323217.20151229164536.66">&lt;h2&gt;... and GIFs!&lt;/h2&gt;
&lt;/section&gt;
&lt;/section&gt;
					</t>
<t tx="40323217.20151229164536.67">&lt;section data-transition="slide" data-background="#4d7e65" data-background-transition="zoom"&gt;
&lt;h2&gt;Background Transitions&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164536.68">&lt;p&gt;
						Different background transitions are available via the backgroundTransition option. This one's called "zoom".
					&lt;/p&gt;
					</t>
<t tx="40323217.20151229164536.69">&lt;pre&gt;
@others
&lt;/pre&gt;
				&lt;/section&gt;

				&lt;section data-transition="slide" data-background="#b5533c" data-background-transition="zoom"&gt;
					</t>
<t tx="40323217.20151229164536.7">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="40323217.20151229164536.70">&lt;code&gt;Reveal.configure({ backgroundTransition: 'zoom' })&lt;/code&gt;</t>
<t tx="40323217.20151229164536.71">&lt;h2&gt;Background Transitions&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164536.72">&lt;p&gt;
You can override background transitions per-slide.
&lt;/p&gt;
					</t>
<t tx="40323217.20151229164536.73">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;


					</t>
<t tx="40323217.20151229164536.74">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background-transition="zoom"&amp;gt;&lt;/code&gt;</t>
<t tx="40323217.20151229164536.75">&lt;section&gt;
    &lt;h2&gt;Pretty Code&lt;/h2&gt;
    @others
&lt;/section&gt;
					</t>
<t tx="40323217.20151229164536.76">&lt;pre&gt;
    &lt;code data-trim contenteditable&gt;
    @others
    &lt;/code&gt;
&lt;/pre&gt;
					</t>
<t tx="40323217.20151229164536.77">function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
</t>
<t tx="40323217.20151229164536.78">&lt;p&gt;
Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.
&lt;/p&gt;



					</t>
<t tx="40323217.20151229164536.79">&lt;section&gt;
&lt;h2&gt;Marvelous List&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164536.8">&lt;div class="reveal"&gt;
@others
&lt;/div&gt;

</t>
<t tx="40323217.20151229164536.80">&lt;ul&gt;
@others
&lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="40323217.20151229164536.81">
&lt;li&gt;No order here&lt;/li&gt;
</t>
<t tx="40323217.20151229164536.82">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="40323217.20151229164536.83">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="40323217.20151229164536.84">&lt;li&gt;Or here&lt;/li&gt;
					</t>
<t tx="40323217.20151229164536.85">&lt;section&gt;
&lt;h2&gt;Fantastic Ordered List&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164536.86">&lt;ol&gt;
@others
&lt;/ol&gt;
&lt;/section&gt;

					</t>
<t tx="40323217.20151229164536.87">
&lt;li&gt;One is smaller than...&lt;/li&gt;
</t>
<t tx="40323217.20151229164536.88">&lt;li&gt;Two is smaller than...&lt;/li&gt;
						</t>
<t tx="40323217.20151229164536.89">&lt;li&gt;Three!&lt;/li&gt;
					</t>
<t tx="40323217.20151229164536.9">&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;

</t>
<t tx="40323217.20151229164536.90">&lt;section&gt;
&lt;h2&gt;Tabular Tables&lt;/h2&gt;
					</t>
<t tx="40323217.20151229164536.91">&lt;table&gt;
@others
&lt;/table&gt;
&lt;/section&gt;


					</t>
<t tx="40323217.20151229164536.92">&lt;thead&gt;
@others
&lt;/thead&gt;
</t>
<t tx="40323217.20151229164536.93">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="40323217.20151229164536.94">
&lt;th&gt;Item&lt;/th&gt;
</t>
<t tx="40323217.20151229164536.95">&lt;th&gt;Value&lt;/th&gt;
								</t>
<t tx="40323217.20151229164536.96">&lt;th&gt;Quantity&lt;/th&gt;
							</t>
<t tx="40323217.20151229164536.97">&lt;tbody&gt;
@others
&lt;/tbody&gt;
					</t>
<t tx="40323217.20151229164536.98">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="40323217.20151229164536.99">
&lt;td&gt;Apples&lt;/td&gt;
</t>
<t tx="40323217.20151229164557.1">@language xml
@tabwidth -4
@others

</t>
<t tx="40323217.20151229164557.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="40323217.20151229164557.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="40323217.20151229164557.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="40323217.20151229164557.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="40323217.20151229164557.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229164557.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229164557.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;四設計二乙cpwork&lt;/h1&gt;
    &lt;p&gt;40323217 李伯皇 2015/9/24&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="40323217.20151229164557.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;CP筆記&lt;/h1&gt;
    &lt;p&gt;利用Git和Github來達到版次管理，並且在近端測試再把資料推送至遠端，在電腦輔助下把重複性的動作藉由批次檔達到我們的需求。第一週重點: git add . -&gt; git commit  -m "推送依據" -&gt; git push origin master(非常重要,推送至起初的master) 第二週重點: 1.git clone 網址 -&gt; revel貼上(除README.md) -&gt; push回去遠端 -&gt; 在推送前要先建分支 -&gt; git branch 分支 -&gt; git checkout 分支名子 -&gt; revel-gh-pages 覆蓋 -&gt;推回去所建立的分支 -&gt;利用leo進行檔案更改. 補充筆記: 1. git config --global.user "名子" 和 git config --global.email"輸入信箱" 這兩點是要確認身分 2. pip install pelican markdown 是下載模組.  &lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="40323217.20151229164557.9">&lt;section&gt;
    &lt;h1&gt;自評分數75分&lt;/h1&gt;
    &lt;p&gt;我發覺在git branch (git checkout) 這點很重要在推送資料時才知道是推送至分支還是master因為我在這點花了很多時間才弄懂，master檔案要推到master，分支的要推到分支，都要非常清楚自己在每個步驟的重要性一步一步的達到老師的要求，更重要的是英文因為很多第一首的資料都是以英文呈現另外網路上資料都是以英文呈現，看不懂就沒辦法知道解決方法。&lt;/p&gt;
   
&lt;/section&gt;
				
</t>
<t tx="40323217.20151229164603.1">@language xml
@tabwidth -4
@others

</t>
<t tx="40323217.20151229164603.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="40323217.20151229164603.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="40323217.20151229164603.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="40323217.20151229164603.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="40323217.20151229164603.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229164603.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229164603.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;四設計二乙CPwork&lt;/h1&gt;
    &lt;p&gt;40323217 李伯皇 2015/10/11&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="40323217.20151229164603.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;CPW4筆記&lt;/h1&gt;
    &lt;p&gt;1.Sketch → Tangent Arc at Point 選擇兩條線所相接的點,可以使那個點形成圓角並且拖曳相切的點可以改變半徑大小.2.New Group → Extrude, or choose the equivalent button from the toolbar.可以使你所畫的圖,往+x方向長料或者從工具列選擇長料.3.Change the extrusion depth by dragging a point on the extruded face.拉動所指定的面可以使所選擇的面身長或縮短4.New Group -&gt; Sketch in 3D(Shift + 3 建立新平面)5.New Group → Sketch in New Workplane 用在孔的時候必須選擇新平面.

  &lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="40323217.20151229164603.9">&lt;section&gt;
    &lt;h1&gt;自評分數79分&lt;/h1&gt;
    &lt;p&gt;基準面沒有先建立好的話在長料的過程中很容易發生問題,假如在執行過程中有不符合軟體規定會產生破圖(圖框會呈現紅色)所以在執行軟體繪製過程中要特別注意這點,再來就是在畫肋的時候假如沒有先選擇基準點下去畫我發現明明在XY平面下所畫的盡然從側視圖看會跑到後面去(意思是沒有在我所預料的地方下畫圖),所以在畫肋的時候基準點須點好(shift+3)在中線下畫才能夠達到自己的預設,最後在掏孔的時候需要用到(New group-&gt;setch in new workplane)以這平面為基準下去畫要不然會跟肋一樣的產生相同的問題. &lt;/p&gt;
   
&lt;/section&gt;
				
</t>
<t tx="40323217.20151229164608.1">@language xml
@tabwidth -4
@others

</t>
<t tx="40323217.20151229164608.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="40323217.20151229164608.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="40323217.20151229164608.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="40323217.20151229164608.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="40323217.20151229164608.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229164608.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229164608.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;四設計二乙CPwork&lt;/h1&gt;
    &lt;p&gt;40323217 李伯皇 2015/10/17&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="40323217.20151229164608.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;CPW5筆記&lt;/h1&gt;
&lt;p&gt;1.標註尺寸時要按住Ctrl鍵選取兩點-&gt;滑鼠右鍵,就可以去改變尺寸。
     2.零件組合時要靠近所組裝的地方，再去制定建置(不然會離太遠只會顯示距離)
     3.繪製草圖前要先選擇要繪製的平面(例如:前視圖或者右視),在選擇是要拉伸還是選轉(除料時可以用到)
     4.組合限制時可以選擇平面對平面或者自動。

  &lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="40323217.20151229164608.9">&lt;section&gt;
    &lt;h1&gt;自評分數80分&lt;/h1&gt;
    &lt;p&gt;這次的Cero跟上禮拜的solvespace有點大不同地方是solvespace會有個小視窗可以讓你控制是要長料還是上色而且可以看到每個畫圖的步驟，而且約束條件比較明確。Cero的特點是跟介面相對整齊而且功能列完整但約束條件必須透過滑鼠右鍵去選擇，而且組裝零件圖，可以先畫完零件圖之後再選擇組件，就可以把每個所畫的零件圖組合起來，這對機械工程師來講非常重要，因為一個機台或者物件不太可能一次畫完所以先計畫好要先畫什麼，之後再利用這功能一個一個組裝起來，來達到所預設的實體。&lt;/p&gt;
   
&lt;/section&gt;
				
</t>
<t tx="40323217.20151229164612.1">@language xml
@tabwidth -4
@others

</t>
<t tx="40323217.20151229164612.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="40323217.20151229164612.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="40323217.20151229164612.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="40323217.20151229164612.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="40323217.20151229164612.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229164612.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229164612.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;四設計二乙CPwork&lt;/h1&gt;
    &lt;p&gt;40323217 李伯皇 2015/12/27&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="40323217.20151229164612.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;CPW11筆記&lt;/h1&gt;
&lt;p&gt;
1.設定個人Leo和班級Leo。
&lt;br / &gt;
2.畫核桃機零件圖及組合核桃機而核桃機零件可由小組分配去畫自己所分配到的。 
  &lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="40323217.20151229164612.9">&lt;section&gt;
    &lt;h1&gt;自評分數83分&lt;/h1&gt;
    &lt;p&gt;本周由於老師將Uesr的節點刪除，必須利用git reset --hard將版本切換回去有User時找到自己以前的檔案，並且將裡面內容複製過去新版的班級個人，還有就是依小組網頁為主。
&lt;/p&gt;
   
&lt;/section&gt;
				
</t>
<t tx="40323217.20151229164617.1">@language xml
@tabwidth -4
@others

</t>
<t tx="40323217.20151229164617.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="40323217.20151229164617.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="40323217.20151229164617.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="40323217.20151229164617.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="40323217.20151229164617.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229164617.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229164617.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;四設計二乙CPwork&lt;/h1&gt;
    &lt;p&gt;40323217 李伯皇 2015/12/27&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="40323217.20151229164617.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;CPW12筆記&lt;/h1&gt;
&lt;p&gt;
1. Fix . Leo-editor 操作步驟。
&lt;br / &gt;
2.跟著W12-2的投影片用movie呈現。
&lt;br / &gt;
3.利用jupyter 把各小組資料整合進去。
  &lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="40323217.20151229164617.9">&lt;section&gt;
    &lt;h1&gt;自評分數84分&lt;/h1&gt;
    &lt;p&gt;這禮拜目的在於不要用隨身碟開起
Star，由於用隨身碟啟動Star速度太慢，因為工作環境不是在C槽所以說要利用fix的功用在每次開機時候設定一下這樣就可以擁有與自己自家的電腦一樣的工作環境 。
    &lt;/p&gt;   
&lt;/section&gt;
				
</t>
<t tx="40323217.20151229164621.1">@language xml
@tabwidth -4
@others

</t>
<t tx="40323217.20151229164621.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="40323217.20151229164621.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="40323217.20151229164621.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="40323217.20151229164621.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="40323217.20151229164621.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229164621.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229164621.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;四設計二乙CPwork&lt;/h1&gt;
    &lt;p&gt;40323217 李伯皇 2015/12/27&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="40323217.20151229164621.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;CPW13筆記&lt;/h1&gt;
&lt;p&gt;
1.使用cero畫圖並組立，小組分配。
&lt;br / &gt;
2.檔案上傳至github並且在小組網誌上能夠顯示，還有把自己所畫零件轉乘.STL檔顯示至班級網站上。
&lt;br / &gt;
3.運用Onshape把自己所分配到的零件畫出來，及輸出零件圖和影片。

  &lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="40323217.20151229164621.9">&lt;section&gt;
    &lt;h1&gt;自評分數85分&lt;/h1&gt;
    &lt;p&gt;Onshape是一個線上繪圖軟體，但由於目前是開發第一代所以使用上還沒有那麼方便，但是由於有版本控制、使用者紀錄、同步控制等優點讓我們在使用上非常方便，但是我發覺再組合上沒有向Cero一樣好，Cero只要指定軸跟面就可以組合但是Onshape需要用轉軸而且在拉身上沒有像Cero一樣能夠把軸跟面分得很清楚，但我相信每個軟體都有它的優點。&lt;/p&gt;
   
&lt;/section&gt;
				
</t>
<t tx="40323217.20151229164625.1">@language xml
@tabwidth -4
@others

</t>
<t tx="40323217.20151229164625.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="40323217.20151229164625.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="40323217.20151229164625.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="40323217.20151229164625.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="40323217.20151229164625.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229164625.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229164625.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;四設計二乙CPwork&lt;/h1&gt;
    &lt;p&gt;40323217 李伯皇 2015/12/28&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="40323217.20151229164625.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;CPW14筆記&lt;/h1&gt;
&lt;p&gt;1.以組為單位寫心得。
&lt;br / &gt;
2.Onspape組立核桃影片。
  &lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="40323217.20151229164625.9">&lt;section&gt;
    &lt;h1&gt;自評分數86分&lt;/h1&gt;
    &lt;p&gt;下星期為自評分數我對我本學期對於電腦輔助設計與實習這們課的心得是雖然很困難但是我能夠在這當中學期到很多跟書上不同的東西，也讓我受益良多，而最後一週Onshape更讓我驚奇讓我平常使用的Soildworks能夠在網際網路上畫圖即時分享，這點真的是分常厲害。&lt;/p&gt;
   
&lt;/section&gt;
				
</t>
<t tx="40323217.20151229164630.1">@language xml
@tabwidth -4
@others

</t>
<t tx="40323217.20151229164630.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="40323217.20151229164630.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="40323217.20151229164630.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="40323217.20151229164630.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="40323217.20151229164630.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229164630.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229164630.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;四設計二乙CPwork&lt;/h1&gt;
    &lt;p&gt;40323217 李伯皇 2015/12/28&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="40323217.20151229164630.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;CPW15筆記&lt;/h1&gt;
&lt;p&gt;1.以組為單位寫心得。
&lt;br / &gt;
2.Onspape組立核桃影片。
&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="40323217.20151229164630.9">&lt;section&gt;
    &lt;h1&gt;自評分數87分&lt;/h1&gt;
    &lt;p&gt;下週就是期末評分了，對於這學期所學習的真的跟一年級所學習到的差很多，但也發覺自己的成長，也發覺這學期的期間中網路的發展與成長你能夠更清楚的看到這世界的改變。&lt;/p&gt;
   
&lt;/section&gt;
				
</t>
<t tx="40323217.20151229201516.1">@language xml
@tabwidth -4
@others

</t>
<t tx="40323217.20151229201516.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="40323217.20151229201516.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="40323217.20151229201516.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="40323217.20151229201516.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="40323217.20151229201516.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229201516.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229201516.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;四設計二乙CPwork&lt;/h1&gt;
    &lt;p&gt;40323217 李伯皇 2015/12/29&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="40323217.20151229201516.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;CPW6筆記&lt;/h1&gt;
&lt;p&gt;
Cero paramrtic實際上就是大家所說的Pro-e的昇級版，雖然我沒使用過Pro-E但是我覺得Cero很好用他不僅在2D草圖繪製上很方便在3D限制條件更是有自動鎖孔或面的功能。
&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="40323217.20151229201516.9">&lt;section&gt;
    &lt;h1&gt;自評分數85分&lt;/h1&gt;
    &lt;p&gt;我知道我在期中考的成績不是很好所以我想要在期末考時候把以前沒有補齊的功課補齊讓老師看到我們有心要過，有心想要把這堂課學好。&lt;/p&gt;
   
&lt;/section&gt;
				
</t>
<t tx="40323217.20151229202015.1">@language xml
@tabwidth -4
@others

</t>
<t tx="40323217.20151229202015.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="40323217.20151229202015.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="40323217.20151229202015.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="40323217.20151229202015.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="40323217.20151229202015.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229202015.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229202015.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;四設計二乙CPwork&lt;/h1&gt;
    &lt;p&gt;40323217 李伯皇 2015/12/29&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="40323217.20151229202015.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;CPW7筆記&lt;/h1&gt;
&lt;p&gt;
solvespace跟Cero的差別在於，由於Cero檔案大小很大，而solvespace的檔案大小只有2.3MB所以說solvespace不好用一定有它的原因，老師是希望我們可以用簡單工具也可以達到他的要求，因為在未來不可能想要什麼工具就有什麼工具。
&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="40323217.20151229202015.9">&lt;section&gt;
    &lt;h1&gt;自評分數85分&lt;/h1&gt;
    &lt;p&gt;我知道我在期中考的成績不是很好所以我想要在期末考時候把以前沒有補齊的功課補齊讓老師看到我們有心要過，有心想要把這堂課學好。&lt;/p&gt;
   
&lt;/section&gt;
				
</t>
<t tx="40323217.20151229202138.1">@language xml
@tabwidth -4
@others

</t>
<t tx="40323217.20151229202138.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="40323217.20151229202138.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="40323217.20151229202138.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="40323217.20151229202138.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="40323217.20151229202138.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229202138.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229202138.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;四設計二乙CPwork&lt;/h1&gt;
    &lt;p&gt;40323217 李伯皇 2015/12/29&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="40323217.20151229202138.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;CPW8筆記統整&lt;/h1&gt;
&lt;p&gt;1.第一週~第二週:了解支架架構及如何推送。
&lt;br / &gt;
2.第四週:了解solvespace基本用法並繪出圖形。
&lt;br / &gt;
3.第五週:學會Cero基本用法及會出零件圖。
&lt;br / &gt;
4.第六週:原本畫腳踏車變成畫核桃機圖。
&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="40323217.20151229202138.9">&lt;section&gt;
    &lt;h1&gt;自評分數85分&lt;/h1&gt;
    &lt;p&gt;本週為統整週將老師以前所上到的東西統整一下方便自己在往後可以更清楚這份資料的來源。&lt;/p&gt;
   
&lt;/section&gt;
				
</t>
<t tx="40323217.20151229202232.1">@language xml
@tabwidth -4
@others

</t>
<t tx="40323217.20151229202232.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="40323217.20151229202232.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="40323217.20151229202232.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="40323217.20151229202232.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="40323217.20151229202232.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229202232.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20151229202232.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;四設計二乙CPwork&lt;/h1&gt;
    &lt;p&gt;40323217 李伯皇 2015/12/29&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="40323217.20151229202232.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;CPW10筆記統整本學期課程&lt;/h1&gt;
&lt;p&gt;1.資料傳輸
&lt;br / &gt;
2.溝通:引導閱讀、錄製影片、投影片
&lt;br / &gt;
3.旅遊、商務
&lt;br / &gt;
4.nutcracker分析及畫圖
&lt;br / &gt;
5.Solvespace and Cero parametric 
&lt;br / &gt;
6.運算
&lt;br / &gt;
7.3D print 
&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="40323217.20151229202232.9">&lt;section&gt;
    &lt;h1&gt;自評分數85分&lt;/h1&gt;
    &lt;p&gt;本週老師是將以後上課會運用的東西進一步整理  ，有些功能部分還不是很清楚。&lt;/p&gt;
   
&lt;/section&gt;
				
</t>
<t tx="40323217.20160104214807.1">@language xml
@tabwidth -4
@others

</t>
<t tx="40323217.20160104214807.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="40323217.20160104214807.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="40323217.20160104214807.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="40323217.20160104214807.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="40323217.20160104214807.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20160104214807.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="40323217.20160104214807.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;四設計二乙CPwork&lt;/h1&gt;
    &lt;p&gt;40323217 李伯皇 2016/1/4&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="40323217.20160104214807.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;CPW16筆記&lt;/h1&gt;
&lt;p&gt;1.Onshape上把限制條件加上去。


&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="40323217.20160104214807.9">&lt;section&gt;
    &lt;h1&gt;自評分數85分&lt;/h1&gt;
    &lt;p&gt;很謝謝老師這學期的指導，讓我們看到原來一門課可以學到這麼多東西，雖然每當做功課的時候都哇哇叫，實在很難，但是匯了之後就知道原來不難，難是難在自己不敢去面對。&lt;/p&gt;
   
&lt;/section&gt;
				
</t>
<t tx="amd.20150913232631.1"></t>
<t tx="amd.20150913232631.2">QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    background-color: #ffffec; /* Leo's traditional tree color */
    selection-color: black; /* was white */
    selection-background-color: lightgrey;
    /* font-family: SansSerif; */
    /*font-family: DejaVu Sans Mono;*/
    font-family:YaHei Mono;
    /* 標題字型大小設定 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit {
    background-color: cornsilk;
    selection-color: white;
    selection-background-color: blue;
    /*font-family: DejaVu Sans Mono;*/    
    font-family:YaHei Mono;
    /* 沒有特別對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The log panes */
QTextEdit {
    background-color: #f2fdff;
    selection-color: red;
    selection-background-color: blue;
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* log font 大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The body pane */
QTextEdit#richTextEdit {
    background-color: #fdf5f5; /* A kind of pink. */
    selection-color: white;
    selection-background-color: red;
    /*font-family: DejaVu Sans Mono;*/
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* 內文字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLabel {
    font-family:YaHei Mono;'CherryPy', 'pytz', 'mako', 'beautifulsoup4', 'pymysql', 'peewee'
    /* 下方的 Minibuffer 標題字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/* Editor labels */
QLineEdit#editorLabel {
    background-color: #ffffec;
    font-family:YaHei Mono;
    /* 沒有直接對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
    border: 2px;
    margin: 2px;
}</t>
<t tx="amd.20150913232631.3">horizontal: body pane to the left
vertical: body pane on the botton</t>
<t tx="amd.20150919102739.1">主要為 reveal.js 的簡報目錄架構, 其他子目錄為

images - 存放簡報與 pelican 網誌所需要的影像檔案

pelican - 存放 pelican 專案資料檔, 並且設法讓 pelican 所產生的 output 檔案直接存放到上層 reveal.js 根目錄

content/notebook - 存放 Jupyter 的 IPython notebook 檔案, 然後再由 pelican 設定, 將內容放入 blog 文章中

</t>
<t tx="amd.20150919103357.1">打算利用

pelican pelican -o ./../ -s publishconf.py

-o 指定 ouput 所在目錄, 這裡使用上一層目錄, 

-s 則指定 setting, 這裡採用 publishconf.py 中的設定

將位於專案中 pelican 目錄內的 .md 檔案, 轉為 html 網誌格式, 然後存在 reveal.js 的架構目錄中

也就是 index.html 是由 pelican 控制</t>
<t tx="amd.20151007224830.1">安裝

sudo pip3 install jupyter

執行

jupyter notebook
</t>
</tnodes>
</leo_file>
